### ISSUE TITLE
Usernames allow UTF-8 characters

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#1]
This breaks user profiles from loading. IE: https://crowdmap.com/user/v%C3%A4%C3%A4t%C3%A4m%C3%B6inen/ doesn't load. I think we should limit these to standard latin alpha-numeric characters.

Ping @evansims

**Comment by evansims** [comment]
How do you think we should approach this? Convert non-latin characters to latin equivalents? Strip them all together? Show a warning in the UI during registration, or just do the conversion automatically?

**Comment by brianherbert** [comment]
That's tricky, I think we should just force non-latin on registration. I'm afraid if we try and do anything fancier than that and people will get confused. It also keeps us from having to do a conversion process. 

I think we need to validate the text as not containing UTF-8 on input in the UI and return an error on registration. In my experience, people using the Internet in countries with non latin script understand they can't use UTF-8 usernames in general. Even in Korea, usernames for services are in latin.

Maybe we can introduce UTF-8 usernames in the future but it's probably best to keep it simpler now.

Ping @rjmackay - What are you guys doing in Ushahidi v3 with UTF-8 and usernames?

**Comment by evansims** [comment]
Alright, new username policy is live.
1. Characters in username must now be standard alphanumeric.
2. Underscores are supported for concatenation.
3. Usernames must begin with an alphabet character.

**Valid Examples:**
evansims
EvAnSiMs
evan_sims
evansims123

**Invalid Examples:**
_evansims
evan.sims
123evansims
εvαηsιмs
