### ISSUE TITLE
External attachments need beautification. Pretty ugly right now. #css #design

### ISSUE THREAD

**Issue by evansims** [ushahidi/crowdmap-issues#10]
![Screenshot_4_13_13_3_37_PM](https://f.cloud.github.com/assets/3093/377095/156260ca-a47a-11e2-9763-699828f05367.png)

**Comment by evansims** [comment]
Considerable progress towards this today; should have it finished tomorrow.

**Comment by brianherbert** [comment]
Orly? Can't wait to see it ;)

**Comment by brianherbert** [comment]
I'm going to close this. There's another issue open for styling blockquotes #52
