### ISSUE TITLE
Switch to uxImage from Hisrc; support lazy loading of post images

### ISSUE THREAD

**Issue by evansims** [ushahidi/crowdmap-issues#100]
I'm going to swap us out from using the hisrc plugin to [my uxImage library](https://github.com/evansims/uximage), rather than continuing to try to retrofit the one to do what I've already built.

The big win here is we'd be able to support lazy loading of post media, which will make scrolling (especially infinite scrolling) much more manageable on mobile devices, where memory constraints are a concern.

**Comment by brianherbert** [comment]
Sounds a-okay to me.

**Comment by evansims** [comment]
Done!

![](https://dl.dropboxusercontent.com/u/23890/iamsogreat.jpg)
