### ISSUE TITLE
Click on User avatar fails

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#101]
From https://crowdmap.com/search/?q=%23cmupdates

Click on http://dl.dropbox.com/u/34693557/Screenshots/9w.png

Click on user avatar icon - http://dl.dropbox.com/u/34693557/Screenshots/9x.png

**Comment by evansims** [comment]
This is related to #95; the author details aren't being passed properly from search queries to the API. We'll be able to knock both these out at the same time.

**Comment by evansims** [comment]
Fixed !
