### ISSUE TITLE
Improve logged out user experience, discoverability

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#102]
```
If I click on search, would it not be helpful to show all recent reports?
Or allow from the front page to see recent reports as a taste to the content posts available
```

Logged out users should see the post stream

**Comment by evansims** [comment]
I'm not sure I follow ya. The front page already displays all recent posts?

We will be offering "global" and "personal" post streaming soon, so we'll be splitting the views up between just users you follow and everyone on the network, and let you hot swap between them

**Comment by heatherleson** [comment]
You can see posts if you 1. find a user 2. search for content.

Imagine you are new. You want to see the added value.

Landing page - no view into the content available, no featured post to wrap your head around the new vision: http://dl.dropbox.com/u/34693557/Screenshots/a1.png

Create a post - no example of a successful post - http://dl.dropbox.com/u/34693557/Screenshots/a2.png

Search page - no examples of existing posts to think about. http://dl.dropbox.com/u/34693557/Screenshots/a3.png

By demonstrating examples hot or leader topics, you give people an access point to learn and share.

**Comment by evansims** [comment]
I think you need to give the homepage a refresh; users see all of the post stream on their homepage. Are you talking about logged out users specifically? I do agree logged out users should see the post stream too. Our user landing page needs a lot of work in regards to discoverability; it's not very enticing as it is, and very limiting.

I don't believe the search page should display a default post stream though; it will make it unnecessarily heavy. The global posts stream will encompass that functionality.

**Comment by heatherleson** [comment]
yes, logged out users. 

Ok about search page. Trying to document : )

**Comment by evansims** [comment]
Absolutely, I appreciate it! I do agree our logged out experience is garbage right now. I'm going to assign myself to this and take a stab at improving it this week.

**Comment by evansims** [comment]
Hi Heather,

I've done a major reworking of our new user experience today. Would you mind checking it out and giving me your impressions? https://crowdmap.com/welcome (You'll need to be signed out, or it will just redirect you to /posts.)

/cc @brianherbert

**Comment by heatherleson** [comment]
Mobile or other?  Thanks! Will do so tomorrow. I am trying to attain my CM Tinker badge.

**Comment by brianherbert** [comment]
When I click on the login button on the new homepage and then click the field to enter my password, it refreshes the page and switches me to classic.

EDIT: Found the culprit. #166

**Comment by evansims** [comment]
What do we think of the new design? Should we expand on anything there?

One big UX hindrance I've noticed with our mobile logged out experience — we don't make login and registration available without accessing the slider menu, which isn't obvious. We need to add buttons for that in the /welcome UI somewhere, but I'm not quite sure where to fit those in yet.

**Comment by brianherbert** [comment]
We had links on the old homepage but they were difficult to spot. Our original thinking was to display a login dialog as soon as the user did anything that required login but I'm not sure we execute that well.

How about we add another row of buttons below posting/searching for login/create account?

**Comment by heatherleson** [comment]
Pardon my delay.

The crowdmap beta logged out experience is awesome. the ticker of Map _insert_ is cool, but a touch fast to read.

I logged out and switched to crowdmap classic. Then, as people do, I tried to use the FF back and forward buttons. Received the following views. 
![e4](https://f.cloud.github.com/assets/1216707/553811/185dbb12-c392-11e2-99ef-0ce16b5bc455.png)
![Uploading e5.png . . .]()

**Comment by heatherleson** [comment]
Navigation from Crowdmap Classic to Beta. When users are on the Crowdmap Classic, there is no banner or "switch to crowdmap beta". It is an advertisement for "new Crowdmap", but not necessarily a login for new crowdmap

The page is super busy right now. I see that you hacked in "crowdmap classic" into the site banner as a design workaround. 

![e6](https://f.cloud.github.com/assets/1216707/553845/8e504262-c393-11e2-8456-a69bf14acf82.png)

**Comment by brianherbert** [comment]
The Crowdmap Classic logo isn't a hack, that's the logo.

We need to change the gold banner to be a flip over to the new Crowdmap message. 

We need to keep our tickets on topic. If this isn't related to improving the logged out experience on the new Crowdmap, we need a new issue for it.

**Comment by brianherbert** [comment]
Created #206 for the gold strip being a link back to new Crowdmap.

**Comment by brianherbert** [comment]
What is the "ticker of map insert"?

**Comment by heatherleson** [comment]
The "ticker" is the flash of "Map x" "map y" etc.

**Comment by evansims** [comment]
Alright, I think the original issue has been resolved satisfactorily. Locking this down.
