### ISSUE TITLE
Settings changes to profile, not saving

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#104]
Changed Settings, they did not change, infinite loop

clicked http://dl.dropbox.com/u/34693557/Screenshots/aa.png
Choose my profile
Added bio and changed map layer to OSM
Clicked Save
No dice. 
http://dl.dropbox.com/u/34693557/Screenshots/ab.png
http://dl.dropbox.com/u/34693557/Screenshots/ac.png

**Comment by evansims** [comment]
This might be another caching related bug. I'll investigate, thanks.

**Comment by heatherleson** [comment]
Logged out and back in. Settings changed on main login screen: http://dl.dropbox.com/u/34693557/Screenshots/ah.png (map layer changed, can't verify if bio remained. ) The change is not on the profile screen under account settings - http://dl.dropbox.com/u/34693557/Screenshots/ai.png

**Comment by evansims** [comment]
Can your try heading to /me/profile/settings/ and refreshing the page; do the values look right now or are they still old?

**Comment by heatherleson** [comment]
https://crowdmap.com/heatherleson/profile/settings/
http://dl.dropbox.com/u/34693557/Screenshots/an.png

**Comment by evansims** [comment]
Sorry, working from my phone at the moment and don't have the URLs handy. Try /user/me/settings/

**Comment by evansims** [comment]
I've reworked a great deal of how we handle routing and caching tonight which should avoid this and the classic<->new switching problems we've been seeing.

Note that because your browser already has a cache of the old headers in memory you may want to clear your browser history/data and start fresh before re-testing this.

**Comment by heatherleson** [comment]
Ok, caching flow better. Cleared cookies, but I am hitting a settings change loop.   Settings changed, but My Profile does not close:

Actions:
1. login to crowdmap.com (new version)
2. click "my profile"
3. click "account settings". 
4. View, make minor text (bio) change, scroll to bottom, click done
Result - window does not complete - http://dl.dropbox.com/u/34693557/Screenshots/aw.png

**Comment by heatherleson** [comment]
Update: logged into new Crowdmap. clicked "switch to crowdmap classic".  Successfully switched, but had to log back in. Thank you! I can document that: https://wiki.ushahidi.com/display/WIKI/Switching+between+Crowdmap+and+Crowdmap+Classic

**Comment by evansims** [comment]
WIth the caching bug on this fixed, I've transitioned us to a new ticket to cover the UX for the done button.
