### ISSUE TITLE
Caching and login loop

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#105]
Caching issue cited in #104 is not fixed. Opening a new ticket as this is a larger issue for existing users:

Heather@textontech.com - in order to be able to login into new crowdmap on ff. I had to clear all my crowdmap.com cookies manually in firefox.

Brendan attempted to login with his current crowdmap user id: axelbrendan. It would not work. So, he created a different one as a work around. 

Summary:
exisiting users on new crowdmap using firefox may encounter cache login loop. Their current crowdmap user id may not work. 

Other related login bugs:
https://github.com/ushahidi/Ushahidi_Web/issues/722 (This is Csrf loop, but people encounter after multiple login attempts due to caching on ushahidi platform and crowdmap)
https://github.com/ushahidi/Crowdmap/issues/159 (crowdmap classic bug)

**Comment by evansims** [comment]
I need more information; it sounds like this is two or three separate issues.

The caching bug is strictly related to pages not representing their proper state, and that should be fixed now. Any login problems are something completely different. We also use a totally different authentication platform, so no Classic bugs apply to New.

How is login failing? Is there an error? What happens?

**Comment by heatherleson** [comment]
https://github.com/ushahidi/crowdmap-issues/issues/106

**Comment by evansims** [comment]
OK, so #106 is a separate issue? I need clarification, though. When we say

```
Brendan attempted to login with his current crowdmap user id: axelbrendan. It would not work. So, he created a different one as a work around.
```

Need to know how it doesn't work; is there an error?

**Comment by brianherbert** [comment]
They need to use their classic email address, by the way. The usernames on classic are map specific, which is why we only prompt for email addresses everywhere on classic.

**Comment by aoduor** [comment]
Could this be related to https://github.com/ushahidi/crowdmap-issues/issues/122?

**Comment by brianherbert** [comment]
Is there an issue? The user tried logging in with a username, which doesn't exist on Crowdmap Classic or Crowdmap, only on the individual Ushahidi maps.

I think we can close this but please correct me if I'm wrong.

**Comment by evansims** [comment]
@aoduor Nope. That's just a CrowdmapID.com frontend bug. No relation here.

**Comment by aoduor** [comment]
Comprende.

**Comment by evansims** [comment]
Closing as this seems to have been a case of confusion about the login process rather than a bug; we've made updates the login UI to make things a bit clearer.
