### ISSUE TITLE
Community Engagement signup

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#107]
In the about page http://dl.dropbox.com/u/34693557/Screenshots/a-.png or in their initial "thanks for signing up email", can we have a link to have them sign up for Team Crowdmap updates?

We can use this for tips, teasers, special deals and community updates? 

It should go to a Campaign monitor list.

**Comment by brianherbert** [comment]
Actually, I was talking with Evan about this so we can include a newsletter checkbox on signup. It makes things a little less simple (grumble grumble) but we have to ask. Let's consider this ticket the ticket for adding that.

**Comment by heatherleson** [comment]
Thank you! Would you like me to write text around that?

**Comment by brianherbert** [comment]
I think it's just a checkbox but if you have 4-6 words to describe the list, that would be okay.

**Comment by brianherbert** [comment]
This is added.

Closing.

**Comment by heatherleson** [comment]
I will test. Issues like this should maybe stay open until I can test?

**Comment by brianherbert** [comment]
If you would like to test the newsletter checkbox on signup, that's fine. You won't be able to confirm if it works in the database, although I see people with various settings already in the db.

**Comment by heatherleson** [comment]
Ok, I have an existing account, so there is no way for me to test. I will open a separate issue to have this in the account settings as an opt in for crowdmap communications.
