### ISSUE TITLE
Settings page needs to redirect to profile after hitting 'done'

### ISSUE THREAD

**Issue by evansims** [ushahidi/crowdmap-issues#108]
Transitioning from #104. When in standalone page mode (not modal) the "Done" button does not redirect the user back to their profile.

**Comment by brianherbert** [comment]
Moving this to ASAP since we are dropping users here now after maps are created. Working on this now.

**Comment by brianherbert** [comment]
This is an overall fix for the modal-close buttons when these windows are not being displayed as modals. Clicking on

``` html
<a href="/somelink" class="modal-close">Done</a>
```

style links now should send them to the /somelink URL in the href. Otherwise, the window will just close.
