### ISSUE TITLE
About page edits

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#109]
In the about page - http://dl.dropbox.com/u/34693557/Screenshots/a-.png
1. Could we include links to the main Crowdmap wiki page home (now that this is created). I added "known issues" and "crowdmap community announcements" for archives
2. https://crowdmap.com/faq
3. this should include a link back to the wiki home for FAQs and docs
   https://wiki.ushahidi.com/display/WIKI/Crowdmap

**Comment by brianherbert** [comment]
How should we link to the FAQ on Crowdmap.com if we redirect our URL for it to the wiki?

We already have links to the wiki on the Community Resources page. I changed the Ushahidi Wiki link to Crowdmap Wiki.

**Comment by heatherleson** [comment]
I think that you should keep the main FAQs you have on the crowdmap site, but at the bottom of the FAQ page, simply link back the wiki article for "more FAQs". The wiki is a fast edit. If we have to push people to the wiki as new questions arise, we can use the FAQs there to fill in gaps and support 

Heather

**Comment by brianherbert** [comment]
This can be done.

**Comment by evansims** [comment]
Confirmed fixed in forthcoming UI update.
