### ISSUE TITLE
Should we hide common country names by default? #code #design #ux

### ISSUE THREAD

**Issue by evansims** [ushahidi/crowdmap-issues#11]
Should we filter out commonly recognized country names in summary views? The full string feels unnecessarily "heavy."

![Screenshot_4_13_13_3_39_PM](https://f.cloud.github.com/assets/3093/377097/5bf3c286-a47a-11e2-89fb-b7aeebb6e053.png)

**Comment by brianherbert** [comment]
That's actually the full place name in the db. It might be hard to try and parse those every time. We could try and do something on the geocoding step.

**Comment by evansims** [comment]
Oh, I understand, I just meant at rendering time. I was just thinking on the frontend as a Handlebars helper doing a rtrim sort of deal on a list of super common country names. Something to ponder, anyway.

**Comment by evansims** [comment]
Closing this as unnecessary and silly.
