### ISSUE TITLE
Get Plus page

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#110]
The Get Plus page - http://dl.dropbox.com/u/34693557/Screenshots/b0.png 

-perhaps include a link to the wiki page with more about the security and legal ness of this? if so, please add details.  https://wiki.ushahidi.com/display/WIKI/Crowdmap+-+Advanced+Features

Assuming a lawyer looked at it. 
- do we need to mention the provider name for this 'payment' service. I tend to get nervous paying things online without a "paypal" or approved by visa, mastercard etc notice. 

-i find the notice about the $1.00 charge to be in too small of print to read
-Will people get a renewal notice for annual payments, will it be a 3-month warning, 1 month and 1 week notice

Update: Email receipt confirmation notes expiry date and renewal process.

**Comment by brianherbert** [comment]
Lawyers drafted all of our legal documents.

Aside from the smaller text, what needs to be addressed?

**Comment by heatherleson** [comment]
Great!

I find it uncomfortable to provide my credit card information on any page with out special certified notices. 

However, increasing the text size and adding more details about the legal, provider and security measures on the wiki will go a long way in helping build trust.

**Comment by brianherbert** [comment]
I added a badge showing that our payments are handled with the secure Braintree. Recurly doesn't have a badge handy but I think this should do. The badge links to https://www.braintreegateway.com/merchants/dnw56wnfg324sbwz/verified which says:

"Ushahidi Inc. takes credit card data security very seriously. For that reason, we use Braintree to securely handle credit card information. Braintree is a Validated Level 1 PCI DSS Compliant Service Provider. Learn more about Braintree security practices."

As far as the text is concerned, I understand it's a bit hard to read  but I'm afraid to add a bunch of big text around the Subscribe button.

**Comment by heatherleson** [comment]
all good. thank you
