### ISSUE TITLE
My profile not resolving

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#111]
Clicked on "my profile" in the user menu

Received:
Crowdmap Error   on https://crowdmap.com/user/heatherleson

The application could not run because of the following error:
Details
Code: 8
Message: Undefined offset: 1
File: /var/www/core/routes/user.php
Line: 216
Trace
#0 /var/www/core/routes/user.php(216): Slim::handleErrors(8, 'Undefined offse...', '/var/www/core/r...', 216, Array)
#1 [internal function]: {closure}('heatherleson')
#2 /var/www/slim/Route.php(395): call_user_func_array(Object(Closure), Array)
#3 /var/www/slim/Slim.php(1145): Slim_Route->dispatch()
#4 /var/www/slim/Middleware/Flash.php(84): Slim->call()
#5 /var/www/slim/Middleware/MethodOverride.php(91): Slim_Middleware_Flash->call()
#6 /var/www/slim/Middleware/PrettyExceptions.php(65): Slim_Middleware_MethodOverride->call()
#7 /var/www/slim/Slim.php(1097): Slim_Middleware_PrettyExceptions->call()
#8 /var/www/index.php(62): Slim->run()
#9 {main}

**Comment by brianherbert** [comment]
This has been fixed.

@evansims - I posted a comment for followup at https://github.com/ushahidi/Crowdmap-New-UI/commit/37004c8bfa2f4635bdabbe587905738f16f63268#commitcomment-3128790
