### ISSUE TITLE
Deleting a map

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#112]
Attempted to delete a map. the window does not roll back to "My profile" after I click "delete map". It is confusing that I that 1. I don't get a notice that the map is deleted and to click done and 2. that I need to click "done" to return to the main profile page. 
http://dl.dropbox.com/u/34693557/Screenshots/b2.png

When I click "done", the map seems to still be live - http://dl.dropbox.com/u/34693557/Screenshots/b3.png (This is the screen I return to.  It also exists in my map home page - http://dl.dropbox.com/u/34693557/Screenshots/b4.png

**Comment by brianherbert** [comment]
Commented this out for now since it's not wired up. Thanks :+1: 

I'll open another ticket for getting this in.
