### ISSUE TITLE
Push Posts 

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#113]
Is there an ifft or other shortcut service that can push my elected posts from Twitter to Crowdmap or Facebook to Crowdmap?

I have been posting "Garden Reports" to twitter to my friends for over 3 years. It would be great to have "push technology" post it to Crowdmap. I am aware that I could post to Crowdmap then back to Twitter, but the workflow is rugged.

**Comment by brianherbert** [comment]
If you have connections at IFTTT to get Crowdmap as a channel, please hook me up ASAP.

We have Instagram auto posting but it's currently not working in production (Issue #57). We are going to add Twitter as soon as we have the time and energy to get it in there.

Facebook is a closed ecosystem and we are not allowed to take posts out of their walled garden and put them on the public Internet.
