### ISSUE TITLE
Map Privacy settings and Get Plus

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#114]
I installed "get plus" on my profile. Created a map test to see if I could create a 'private one', it asked me to "get Plus" to allow for a private one. The system should recognize my "get plus' status.

http://dl.dropbox.com/u/34693557/Screenshots/b8.png

**Comment by brianherbert** [comment]
Since private maps aren't yet wired up, I need to change that language. Thanks for spotting it.

**Comment by brianherbert** [comment]
I removed these messages. I also opened #117 for getting this support in the API.
