### ISSUE TITLE
Top Crowdmap Classic deployments

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#115]
There are a number of key crowdmap deployments. It looks like anyone could go into new crowdmap and register these crowdmap brand/deployment. 

Should we 
1. reserve the top users' crowdmap to avoid duplication and confusion for a year?
2. notify the top users?

note - crowdmaps.crowdmap.com is not reserved. Are all the ushahidi type things reserved yet?

**Comment by brianherbert** [comment]
It's not possible to reserve the name of an existing deployment.

![screen shot 2013-05-02 at 10 17 18 am](https://f.cloud.github.com/assets/106068/451990/13a800f0-b2c6-11e2-9cb9-cbd7279f497a.png)

**Comment by brianherbert** [comment]
Regarding reserved names, please let us know what you want reserved and we can get it on the blacklist, but shoot us an email with that.
