### ISSUE TITLE
Uploading animated gif returns 500 error in console

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#116]
I'm trying to upload the gif on http://mapbox.com/blog/2006-2013-osm-growth-animated/ (saved to my desktop, then trying to reupload) but it returns a 500 error. I see upload progress get up to 100%, then it waits 30 seconds or so (probably resizing, etc) and then comes back with a 500 error.

Uploading a png seems to work fine.

**Comment by evansims** [comment]
Should be fixed now. We had several layers of software that were still set to their default 60 second timeout. Being a big gif that was taking a bit more than that to process. I've increased the timeout threshold to compensate.

Give it another go and let me know if this resolved things for ya.

**Comment by brianherbert** [comment]
Working now! I think we need to work in the upload status and then flip over to a "processing on server" message or something like that. I'll make another ticket.
