### ISSUE TITLE
Users can create empty posts. #code

### ISSUE THREAD

**Issue by evansims** [ushahidi/crowdmap-issues#12]
![Screenshot_4_13_13_3_43_PM](https://f.cloud.github.com/assets/3093/377098/d3c20ac0-a47a-11e2-9530-46b5104bc5e7.png)

Users should be required to have at least a short message or photo in order to publish a post.

I think we should handle this on the API end and respond with an error on the frontend, rather than trying to handle it the other way around.

**Comment by brianherbert** [comment]
I think we should allow a simple checkin for apps that want to just post geometries or points. Maybe we filter this out in this view?

**Comment by evansims** [comment]
Good point. Yeah, maybe just filtering these out of view. Or maybe take Path's approach and just display check-ins differently from content-worthy posts in the stream. Maybe have a little static map graphic of where they checked in.

**Comment by brianherbert** [comment]
I fixed this on an API level but we still need some error handling on the create form. It will just sit and spin forever. I'll open another ticket for that.

Also, we may need to consider the alternative styling for the location only posts.

Closing.
