### ISSUE TITLE
UI - Account Settings (Map list view)

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#120]
This a minor UI suggestion. It would be nice to have the map base layer list a collapsible field dropdown. This is mainly because it looks daunting with a large list and 'hides' the other items on the "account settings" page. 
http://dl.dropbox.com/u/34693557/Screenshots/bv.png

**Comment by brianherbert** [comment]
I agree. There are a couple other selectors like this that we need to collapse.

**Comment by evansims** [comment]
Agreed! A bit overwhelming and unwieldily at the moment. Marking as 'Soon.'

**Comment by brianherbert** [comment]
Done!
