### ISSUE TITLE
Special Characters in password returns "Incorrect password" error

### ISSUE THREAD

**Issue by aoduor** [ushahidi/crowdmap-issues#122]
Pinging @evansims 

We'd previously noted this issue and it forced me to remove special characters in my password to allow for account set up.

Looks like it's back/not sorted :(. We need a work around before monday :(

**Comment by evansims** [comment]
Hey Angela, I've made a few tweaks to our password handling. Can you give it another try when you have a chance?

**Comment by aoduor** [comment]
hey @evansims, trying to change password back via https://crowdmapid.com and getting this

![screenshot](http://i.imgur.com/7j7jOBE.png)

**Comment by brianherbert** [comment]
Hey Evan, should this be closed here and opened in the CrowdmapID issue tracker?

**Comment by evansims** [comment]
Well, the primary issue in this ticket is related to New Crowdmap, not CrowdmapID. The screenshot is unrelated to the original problem, but I've fixed that. Could we get you to try this again @aoduor and let us know if the original issue is fixed?

**Comment by evansims** [comment]
Presumed fix with recent changes. Please open a new ticket if encountered again.
