### ISSUE TITLE
{low priority} Beta invite codes not working

### ISSUE THREAD

**Issue by aoduor** [ushahidi/crowdmap-issues#123]
I tried out my private beta invite code on a different email address i don't have registered, and it didn't work.

Probably doesn't matter since we're opening it up, but thought it would be good to give you a heads up!

**Comment by evansims** [comment]
Mmm invite codes definitely work, we've had people using them. Which invite code did you try to use? Going to close this since it won't be an issue in a few days, but I'd like to debug this in case we want to reuse the beta invite code in the future. :) :heart:

**Comment by aoduor** [comment]
Yikes! I can't find it now :(.

**Comment by brianherbert** [comment]
Because we're in public beta, there are no more invite codes.

**Comment by aoduor** [comment]
I know :).

Guess we'll park this for when we need it again.
