### ISSUE TITLE
Account activation question

### ISSUE THREAD

**Issue by aoduor** [ushahidi/crowdmap-issues#125]
As is stands now, does a user not activating their account have any effect whatsoever on crowdmap usage? When i sign up successfully, it just redirects me to the homepage straight away (not a bad thing), then I get an email to activate my account. Wondering if we should restrict access until account activation is complete?

ping @brianherbert @evansims

**Comment by evansims** [comment]
Right now it doesn't really do anything noticeable. Internally we flip an 'activated' switch in the user table and mark the email address as confirmed with CrowdmapID. We don't restrict access at the moment, but we should probably treat unactivated accounts as if they were Anonymous.

Right now, Anonymous users have very few restrictions, but my gut tells me that going forward we're going to have some troubles with this. Easily abused and misused, and difficult to moderate. Once this starts presenting itself we can start considering how we approach unactivated accounts too.

**Comment by brianherbert** [comment]
I believe we discussed hiding anonymous posts from the global feed but still allowing it. One of the big things people always ask at events is how they can get anonymous submissions on their maps. I'm a bit hesitant to cripple that process too much.  

I think we can add some settings like not allowing anonymous submissions to a map to help admins control spam if that becomes a problem.

**Comment by evansims** [comment]
That might make sense. I think anonymous posting is important, and I'm not suggesting we cripple that. I'm just saying that we will need to figure out ways of dealing with spam, trolling, hate speech, lude postings, etc. in a manageable fashion. In the context of inactivated accounts, I'm most concerned about spam bots. But we'll cross this bridge when we come to it.

**Comment by brianherbert** [comment]
Sorry I derailed the ticket :dancers: 

If we are going to prevent activity before activation, we should probably check if the user signing up already has a CrowdmapID account and not send an activation email to them. It might be kind of annoying if they already have a Crowdmap account and then they have to activate it all of a sudden.

**Comment by evansims** [comment]
Agreed. We have a 'confirmed' flag in CrowdmapID 2.0 that services can set after a user confirms their email addresses through them (like we're doing now.) We can check this flag in future iterations but I'm hesitant to retroactively apply that flag to all existing accounts
