### ISSUE TITLE
Search from main 'latest posts' page

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#126]
Search retrieves all posts as "nairobi". If folks don't tag a location, does it default to Nairobi.
It looks like people are tagging posts with other locations, but the main search results retrieves all the latest posts irrespective of the 'search' done in the top left hand side box. 

http://dl.dropbox.com/u/34693557/Screenshots/c0.png

**Comment by brianherbert** [comment]
This is an address search to reposition the map. You'll see the map is zoomed over Nairobi in the background. You will need to click Search to search posts.
