### ISSUE TITLE
Detect EU users and inform them of our cookie policies

### ISSUE THREAD

**Issue by evansims** [ushahidi/crowdmap-issues#127]
We should consider detecting EU visitors based on IP and displaying a brief summary of our cookie policy using a fixed position UI element that floats at the bottom of the viewport. The UI element should be visible on all pages at all times until dismissed.

Here's an example I like:
![screen shot 2013-05-03 at 11 57 14 pm](https://f.cloud.github.com/assets/3093/462117/251765b2-b477-11e2-8cbc-6e04b5b783ec.png)

The [EU e-Privacy Directive](http://en.wikipedia.org/wiki/Directive_on_Privacy_and_Electronic_Communications#Cookies) went into effect in May of 2012. It requires websites that track users in non-critical ways to notify visitors to the existence of these tracking measures. Although our 'mission critical' cookies (such as `session`) don't require consent under the law, the fact that we use analytics cookies means we need to spell out our policy.

The [ICO](http://www.ico.org.uk/)'s website says, "An analytic cookie might not appear to be as intrusive as others that might track a user across multiple sites but you still need consent."

I've never heard of anyone getting in trouble for not doing this, but given the global nature of Crowdmap I suppose we should try to follow the regulation for applicable users.

**Comment by brianherbert** [comment]
We have those all mentioned in our privacy policy so we could link to that.

**Comment by evansims** [comment]
Yeah, I was thinking the floating UI element would just give a brief "By using this site, you consent to our storing and accessing cookies on your device. Learn more." with a link to our policy and a dismiss option. Nice and concise.

**Comment by brianherbert** [comment]
Sounds good. We already grab the users location using visitors_location() in the template helper.
