### ISSUE TITLE
Opening and closing additional detail button on posts appends same posts/tags to list

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#128]
This whole meta view is a bit chunky. I think we should just rework it highlight the maps a bit more.

![screen shot 2013-05-05 at 2 43 39 pm](https://f.cloud.github.com/assets/106068/463262/c3dff928-b546-11e2-8b37-1eabea5b0a5c.png)

**Comment by evansims** [comment]
:+1: Agreed

**Comment by brianherbert** [comment]
Btw, I have this task. I might need some help making things look a little nicer when I'm done though.

**Comment by evansims** [comment]
No longer relevant with design changes
