### ISSUE TITLE
Markdown links handled poorly in posts

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#129]
![screen shot 2013-05-05 at 3 09 34 pm](https://f.cloud.github.com/assets/106068/463292/6da9dcbe-b54a-11e2-8b14-6b1a66124b0f.png)

**Comment by evansims** [comment]
That links looks OK now on Production. Did you find a workaround?

**Comment by brianherbert** [comment]
I manually fixed it in the DB. If you post a link using Markdown syntax you'll see how it gets mangled.
