### ISSUE TITLE
Viewing Inbox times out

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#130]
When viewing the inbox (probably only with lots of notifications), I'm getting a 504 timeout.

Screenshot: 
http://cl.ly/image/0V0d2J360K0V

**Comment by evansims** [comment]
Going to close this one as a dupe of #54 as the problem and solution will be the same. :)

**Comment by brianherbert** [comment]
I was looking for that ticket but I was on my phone. Thanks :)
