### ISSUE TITLE
Sign Up message change

### ISSUE THREAD

**Issue by aoduor** [ushahidi/crowdmap-issues#139]
I noticed this message pops up, irrespective of whether this is a non-classic crowdmap user registration or a classic crowdmap user registration. 

![screenshot](http://i.imgur.com/TPWKOFJ.png)

**Comment by brianherbert** [comment]
This does say that the account was already set up on Classic or another Ushahidi product, which should cover everything except the new Crowdmap. You should only see this if that email address hasn't been on the new Crowdmap before.

Am I understanding this wrong?

**Comment by aoduor** [comment]
This is on the sign up page... Basically, this prompt shouldn't be available if i'm completely new to our products. :)

**Comment by brianherbert** [comment]
Nevermind, I think I figured it out. This is a bug!

Can you test this again?

**Comment by aoduor** [comment]
we're all good now :)!
