### ISSUE TITLE
Viewing status of collaborator invite

### ISSUE THREAD

**Issue by aoduor** [ushahidi/crowdmap-issues#140]
So, I created a map, and added collaborators, but can't tell where to see who I invited, and who has accepted or not :(. Would be great to have this in somewhere :)

**Comment by brianherbert** [comment]
This is a known issues and related to #136 which will replace the collaborator settings.

Closing since this will be resolved :rabbit:

**Comment by aoduor** [comment]
slapping self for not checking for related posts! Thank you sir :)

**Comment by brianherbert** [comment]
Hakuna shida!
