### ISSUE TITLE
Photo positioning

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#141]
Posted an upright photo to https://crowdmap.com/posts?r=5578. It flipped the photo sideways. It should recognize the position of the original post.

Feature request related: allow us to edit photos in posts to change direction

**Comment by brianherbert** [comment]
Hmm, I fixed this a couple months ago. We'll have to look into this.

**Comment by evansims** [comment]
Hm. I probably broke it with my recent imaging refactor, but I thought I left all of that alone.

**Comment by evansims** [comment]
Assigning myself; debugging this presently.

**Comment by evansims** [comment]
Hi Heather, I've made some changes to how we handle orientation during the resampling process that should fix this.
