### ISSUE TITLE
Map owner shouldn't be able to unfollow a map

### ISSUE THREAD

**Issue by aoduor** [ushahidi/crowdmap-issues#143]
After creating a map, I opened https://crowdmap.com/map/ushteam and clicked on "following" - just for kicks, and discovered that I can actually follow/unfollow it at will

As the owner(think SuperAdmin), I think the option of unfollowing a map should not be available to me.
Thoughts?

**Comment by brianherbert** [comment]
Why not?

**Comment by aoduor** [comment]
The owner, in essence, is like a superadmin. I'm kinda likening it to removing a superadmin from an account( even though you can still moderate posts). Just a thought.

**Comment by brianherbert** [comment]
What if you set up the worlds most annoying map with lots of contributions but you don't want it to go into your normal feed?

**Comment by aoduor** [comment]
Well, good point taken there - we should probably have this explanation on the docs somewhere, just so that users understand

**runs over to wiki to add**
