### ISSUE TITLE
Posting photos from Android Gallery

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#149]
Trying to post a photo from my android gallery fails. Tried with multiple photos today. I can take a photo and add it, but I can't add from my gallery
1. android, nexus 4.2.1
2. click on photo, search gallery, add regular photo, system crashes. 

Attached photo:
![flowers](https://f.cloud.github.com/assets/1216707/468018/b8dca0dc-b689-11e2-986d-fc5323211cf6.jpg)

**Comment by evansims** [comment]
Can you give me some details on your model of phone (which Nexus model in particular) and what browser you're using? I'm not having issues on my Nexus 7 (4.2.3) or HTC One (4.1.2) with this particular aspect, but we do have some problems I'm aware of with Android. The location picker locks up my browser as well. I suspect these are memory issues that might get fixed when [we transition our inline image handling](https://github.com/ushahidi/crowdmap-issues/issues/100)

**Comment by heatherleson** [comment]
Galaxy nexus 4.2.1
phone browser, phone gallery. 

I normally use FF, but I am just using the default one.

**Comment by evansims** [comment]
Cool, thanks. I'll assign myself this one to debug as well. I somehow ended up being the Android guy in this mix.

**Comment by evansims** [comment]
Unfortunately I haven't had any luck reproducing this. Can you try uploading from https://crowdmap.com/create/post/ and letting me know if it still happens for you?

**Comment by heatherleson** [comment]
If I take a picture while creating a post, then I can add it immediately. I am unable to pull a picture from the Android Gallery as it gives the above size error.  Gallery shot on android
![Uploading Screenshot_2013-06-03-17-18-08.png . . .]()

**Comment by evansims** [comment]
Hi Heather, after a great deal of searching and swearing at the Android SDK, I believe I've tracked down the cause of your upload woes. Could you give it a try when you have a sec?

**Comment by heatherleson** [comment]
Glee, chair dancing!!!!
Fixed. I am so happy

https://crowdmap.com/post/2213/

**Comment by evansims** [comment]
Awesome! Glad to hear it's working!

**Comment by heatherleson** [comment]
Spoke too soon. Tested again and meant to update.  When I tried to add the photos from my phone it failed twice. 

Essentially, it looked like it was adding, spun and then just did not add

![photo not adding](https://f.cloud.github.com/assets/1216707/614531/a61a1f04-ce1e-11e2-8018-48e97f4b0f24.png)

https://crowdmap.com/post/2221/
https://crowdmap.com/post/2219/

**Comment by heatherleson** [comment]
this might have something to do with wifi drop out. Because I tried again - https://crowdmap.com/post/2227/

**Comment by evansims** [comment]
Actually this appears to be a different issue. Uploads just stopped working on desktop too. Opening a separate ticket.
