### ISSUE TITLE
Subscribing to plus doesn't flag the user account immediately; must wait for background process to update. #code

### ISSUE THREAD

**Issue by evansims** [ushahidi/crowdmap-issues#15]
I'll speak with Brian on this. The necessary callbacks should be whitelisted on the server now, but we'll need to have a talk and make sure everything is working as it should be.

**Comment by brianherbert** [comment]
This should be updating automatically. I'll have to look into that.

**Comment by evansims** [comment]
Yeah, it's just something I noticed when I signed up for Plus myself a few days ago. Took a good 5 minutes or so before it switched. Do the callbacks from our payment processor hit the API or the UI? If it's the UI it might be hitting Gatekeeper and mucking things up. (Sorry, I could just look it up for myself, but I'm out to dinner atm. ;)

**Comment by evansims** [comment]
Had a person encounter this bug the other day; https://crowdmap.com/post/1681/

**Comment by brianherbert** [comment]
Yeah, I need to make that a priority this week. I've been asked directly a few times about it.
