### ISSUE TITLE
Ability to read EXIF info in pictures. 

### ISSUE THREAD

**Issue by julianar** [ushahidi/crowdmap-issues#150]
Would be great for Crowdmap to be able to process EXIF data from a photo and grab + assign location easily https://crowdmap.com/post/570/capetown-is-lovely-this-was-at-camps-bay
<-that photo has location information in EXIF and could be auto added as a pin. 
Use Case: Low friction posting from mobile as I lack the patience to go find Camps Bay in the map coz you know I am looking at the sunset and grinning :) 
Hugs!

**Comment by brianherbert** [comment]
We are currently reading this and saving relevant information. We need to hook this up to the location picker.

**Comment by evansims** [comment]
Confirmed fixed in forthcoming UI update.
