### ISSUE TITLE
Unable to add tags to a map

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#151]
Creating a new map. Unable to add tags (https://crowdmap.com/map/whiskyorwhiskey/settings/#)

What happens: I click on tags, the page refreshes and i am unable to add tags. 

http://dl.dropbox.com/u/34693557/Screenshots/c9.png

**Comment by brianherbert** [comment]
Thanks for the report! We'll look into this this week.

**Comment by brianherbert** [comment]
This is fixed. @heatherleson If you could verify, that would be awesome.

Closing.

**Comment by heatherleson** [comment]
Device - mobile - Android Galaxy Nexus
![tags](https://f.cloud.github.com/assets/1216707/501448/a2652080-bc98-11e2-96b3-17f53ba446c1.png)
There was no way to add a tag during the post or after the post is loaded.

**Comment by brianherbert** [comment]
This ticket is for adding tags to maps, not posts.  

As a side note, you can add tags to a post by listing them as hash tags in the post message until we have UI for editing the tag listing.

**Comment by heatherleson** [comment]
https://wiki.ushahidi.com/display/WIKI/Crowdmap+-+Using+tags

**Comment by brianherbert** [comment]
Thanks for the write up ;)
