### ISSUE TITLE
Photo shows wrong size immediately after posting

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/crowdmap-issues#153]
Immediately after posting: (super huge size)
![screen shot 2013-05-07 at 5 12 17 pm](https://f.cloud.github.com/assets/7965/469640/d5a80a58-b6d4-11e2-943a-88aeb331b2e1.png)

After a page refresh: (showing correct size)
![screen shot 2013-05-07 at 5 13 01 pm](https://f.cloud.github.com/assets/7965/469641/dbc3f2b2-b6d4-11e2-89a4-5ac737295132.png)

**Comment by brianherbert** [comment]
Thanks for getting this down as an issue. This has been in the back of my mind for a week or more now.

**Comment by evansims** [comment]
Fixed, thanks! Been meaning to fix that one for awhile too.
