### ISSUE TITLE
Consider reporting a concern a destructive action

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#156]
Based on feedback from a user, we should pop up the "are you sure" destructive warning. There's already provisions to do this fairly easily in the JS.

**Comment by evansims** [comment]
Been meaning to do that. Also wanted to give more context options as to why the post is being reported. Spam? Hate speech? Inappropriate media? That sort of deal.

**Comment by brianherbert** [comment]
This is going to be @aoduor's first task

**Comment by evansims** [comment]
This flow has changed in the forthcoming UI update. Marking bug as obsolete.
