### ISSUE TITLE
Typeahead calls API many times simultaneously when creating a post

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#157]
Opening the create post dialog makes lots of identical calls to the API at this URL: https://api.crowdmap.com/v1/people/brianherbert/follow/?datum=true&session=xxxxxxxx&_=xxxxxxx

![screen_shot_2013-05-09_at_3 40 27_pm](https://f.cloud.github.com/assets/106068/481782/af71c47c-b874-11e2-8def-3fe56c4e8e8b.png)

**Comment by evansims** [comment]
I'll track this one down in the morning

**Comment by evansims** [comment]
Fixed.

Problems —
1. With the addition of inline commenting on the homepage, the number of typeahead-enabled textareas exploded.
2. Typeahead's module was only getting loaded in when the post or comment modals were opened. This is why the datum requests suddenly started appearing en masse. It's also why inline comments weren't showing typeahead suggestions properly.
3. Typeahead didn't have any checks in to determine if a sister object was already loading an identical datum url - so they all tried to do the same thing at the same time.

Fixes —
1/2. Typeahead is now loaded in with all pages.
3. Typeahead objects are now intelligent enough to know if one of their sister objects are already loading the datum they need. They'll wait for their sister's request to complete, then process the datum from their shared cache pool.

We should take solace in knowing that most users probably never experienced this as much of a problem, as they don't have 720 followers to process for every datum request. :grinning:
