### ISSUE TITLE
Flagging a comment/post with a concern makes it go away on the page but it's still there

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#159]
We probably shouldn't remove it from view since it will be there on refresh.

**Comment by evansims** [comment]
I agree, it creates an unnecessary inconsistency. But I'd still like to visually indicate that the post is in a state of moderation to the user. Perhaps a half opacity?

**Comment by brianherbert** [comment]
We could adopt the same "saved' message that we fade in over form fields that we save in the settings panels.

**Comment by evansims** [comment]
Nice, I like that idea!

**Comment by evansims** [comment]
I recently applied a tweak on the API side to hide reported posts from results. A forthcoming UI update applies an opacity filter to posts that have been reported until the page has been refreshed.
