### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#160]
I've added Custom CSS. There are still some quirks that may need to be worked out, like we are still alllowing someone to not close their CSS definitions. However, the CSS should be cleaned up to remove anything potentially harmful.

![screen shot 2013-05-10 at 5 17 53 pm](https://f.cloud.github.com/assets/106068/487096/23b1d270-b94a-11e2-9452-99966d9293fe.png)

**Comment by evansims** [comment]
dat background

**Comment by brianherbert** [comment]
I have noticed while writing the CSS functionality that it's pretty difficult to figure out what styles to override. I think we need to probably still allow custom CSS editing but provide something a little more robust as far as styling goes.

I'm going to close this for now since it's working now on a basic level.
