### ISSUE TITLE
Feature: Hashtags from comments

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#161]
Allow hashtag searches from comments:
The request:
http://dl.dropbox.com/u/34693557/Screenshots/ci.png

The search result:
http://dl.dropbox.com/u/34693557/Screenshots/cj.png

**Comment by brianherbert** [comment]
Hashtags are searchable from comments. There aren't any posts tagged with #hashtags so nothing will come up.
