### ISSUE TITLE
Feature: Save to home page

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#162]
Slideshare has an awesome mobile feature. "save to homepage".   Essentially, the user gets a pop up when they go to the mobile ready site, it asks and then adds a quick link to the ipad for a mobile site. As much as I am excited to ween off apps for responsive design, I like the fast load of one touch and get crowdmapping. 

slideshare.net for testing

No screenshots at this time.

**Comment by evansims** [comment]
That'd be easy enough to do, just a couple extra meta tags in the header. I'll add that this weekend.

**Comment by brianherbert** [comment]
Let's make sure we don't bother the user every time the come to the site asking them to treat our site different than any other though. If this can be a little more subtle, that would be good.

**Comment by evansims** [comment]
What, no giant `<h1><blink><marquee>ADD US TO YOUR HOMESCREEN LOL</marquee></blink></h1>`? :)

**Comment by brianherbert** [comment]
Hah, as long as we avoid: http://idontwantyourfuckingapp.tumblr.com/

**Comment by heatherleson** [comment]
cbc.ca also has a lighter version of this. I find that slideshare.net gives me too many popups on 'save to home page'

**Comment by evansims** [comment]
So my plan was just to leverage iOS's built in feature to prompt users to do this, but it appears they removed that API back in iOS 5, so we'll need a custom solution. I'll probably tie this to our EU cookie notice so we have a unified way of dealing with these sorts of notifications in a non-obnoxious manner.

**Comment by evansims** [comment]
After a great deal of research, I've come to the conclusion that there just isn't a decent way of doing this anymore. Apple has really crippled the functionality. Marking as obsolete.
