### ISSUE TITLE
Location search doesn't work when not approving or denying location access in location picker

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#163]
If you ignore sharing your location (don't select yes/or no when asked if it's okay to use your location) and then try to do a search, nothing happens.

ping @heatherleson

**Comment by heatherleson** [comment]
Do you mean "If ignore 'share my location' in my browser? "  I prefer to force use of location for individual apps and, in this case, crowdmap posts. Sometimes I don't want to give a location or have no time.

**Comment by brianherbert** [comment]
Yeah, you shouldn't have to share or even pick. This is a bug.

**Comment by brianherbert** [comment]
Hey @heatherleson, I made a number of changes to the location picker recently and I'm just now getting to this. I'm unable to reproduce the issue so it may have been fixed.

Any chance you could try this again to confirm? Thanks!

**Comment by heatherleson** [comment]
I tested adding a location last night from my mobile browser.

**Comment by brianherbert** [comment]
How did it go?

**Comment by heatherleson** [comment]
It is hard to scope because there is android lag (separate issue item that Evan is working on). Will try again today

**Comment by brianherbert** [comment]
Hey Heather, how did the test work out?

**Comment by heatherleson** [comment]
works on browser (ff) and mobile (android)
