### ISSUE TITLE
Map settings pages (standalone, not modal) do not work

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#165]
The javascript for these pages is not being loaded. I'm seeing a 404 error for the javascript file.

"NetworkError: 404 Not Found - https://crowdmap.com/assets/js/crowdmap.map.settings.js"

This file exists in the filesystem at that directory, however, trying to access it directly or via a script returns a 404.

Something must be up with the deploy precompilation process with requirejs. I believe this has happened before. @evansims, I don't think I understand the steps you took to resolve this last time.

**Comment by evansims** [comment]
I have the production compression process setup to delete files after merging. If I didn't we'd have multiple copies of the script in memory in cases like this, with all sorts of ugly conflicts going on (and we'd be scratching our heads as to why.) This way  we know when there's a problem spot and its much easier to find.

https://github.com/ushahidi/Crowdmap-New-UI/blob/master/views-new/map/settings.php#L53

It's these onload hacks that screw things up. We're trying to require `crowdmap.map.settings.js` before the merged version we want can be loaded into memory. All inline requires must begin with require(['main']) to avoid this — as main, on production, represents our merged JS asset.

Check out https://github.com/ushahidi/Crowdmap-New-UI/blob/master/views-new/users/settings.php#L311-L329 to see a cleaner method.

**Comment by brianherbert** [comment]
This method doesn't work when the settings are loaded as a modal popup since all script tags are stripped out.

**Comment by evansims** [comment]
Modal requires should be getting added here: https://github.com/ushahidi/Crowdmap-New-UI/blob/master/assets/js/global.js#L415-L485

**Comment by brianherbert** [comment]
Ah, cool. I hadn't seen that.

**Comment by brianherbert** [comment]
Got this sorted. Thanks for the pointers!

Closing.
