### ISSUE TITLE
Map load slow

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#175]
Desktop = FF
Clicked on "maps"
Map load stuck - http://dl.dropbox.com/u/34693557/Screenshots/cy.png

Refreshed screen : http://dl.dropbox.com/u/34693557/Screenshots/cz.png 
Worked.

Noticed this lag on mobile too (android regular browser) (no screens shots for that)

**Comment by evansims** [comment]
This would have to be a network issue, most likely a map thumbnail/avatar getting loaded in slowly or timing out. A refresh working would make sense in this situation as you'd have already cached most of the map avatars in your browser and it would just be getting the ones that failed before.

If my guess here is correct, our new image handling library will also alleviate this issue. I'll revisit this ticket after that is implemented to have you retest for this. Thanks.

**Comment by heatherleson** [comment]
Will test then

**Comment by evansims** [comment]
Hey Heather, the new image library is online. Give this some testing when you have time.

**Comment by heatherleson** [comment]
It may be a network issue, but I find both on web (FF) and android lag at scrolling. Tested on home network and around the city. It is a lot of heavy pictures to load, but not sure how else to test.

**Comment by brianherbert** [comment]
I noticed the images took a long time to load when I was trying to show off https://sweetmaps.crowdmap.com to a friend here.

My guess is it's still trying to download original files, which are potentially huge? I'd say most of my post listings don't show half the images, even after the page and all requests have finished downloading.

**Comment by evansims** [comment]
@heatherleson Laggy scrolling on some devices (especially Android-based devices, for some reason) is a problem we're aware of and trying to work on improving. It seems to be related more with the background map than the images on the page. Lots of screen redraws. But yeah, we're working on it. :)

@brianherbert We practically never download full resolution images now, not with the constraints we impose on the current UI. 90% of the time you're seeing the small version, in fact.

**Comment by evansims** [comment]
Shuttin' this one down as I feel the original issue has been addressed.
