### ISSUE TITLE
Photo sizing

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#176]
Added a photo (jpg) from my laptop. It was taken with a camera.

When I post to Crowdmap, (https://crowdmap.com/post/979/ or http://dl.dropboxusercontent.com/u/34693557/Screenshots/d5.png) the photo does not resize and cannot be edited. thus, the headless giraffe.

Options:
1. resize photos for user
2. give an error message
3. (future) allow for sizing in the product

Github won't let me share the original- "Yowza, that's a big file. Please submit an image file smaller than 5MB. "

**Comment by evansims** [comment]
Yeah, it definitely shouldn't be cropped like this. We don't actually cut the full size photos down. Looking at the image file, it does appear to be intact, so it must be a CSS bug on the frontend side.

I'm in the process of totally revamping how we render images so let me finish that first, and it should fix this issue along with it. Thanks for bringing it to my attention!

**Comment by brianherbert** [comment]
Poor giraffe :crying_cat_face:

**Comment by evansims** [comment]
New image library implemented; bug squashed.

**Comment by evansims** [comment]
Actually, I'm stilling noticing an issue here. Odd. Reopening until I track it down. Gut feeling says it's some errant CSS somewhere.

**Comment by evansims** [comment]
Alright, fixed for real now. :)

![](https://dl.dropboxusercontent.com/u/23890/pffft.gif)
