### ISSUE TITLE
A figure below the top menu bar

### ISSUE THREAD

**Issue by eyedol** [ushahidi/crowdmap-issues#178]
On my android device ( Galaxy Nexus running chrome ), I see a figure below the top menu bar. See the picture below to see what I mean
![screenshot_2013-05-15-13-52-04](https://f.cloud.github.com/assets/73175/505323/f7617f6e-bd1c-11e2-9a78-1bfda4abe43a.png)

**Update** Not sure if it supposed to be there

**Comment by brianherbert** [comment]
Do you still see this? I removed it yesterday.

**Comment by brianherbert** [comment]
Actually, I see it now. I don't know how this is possible since I actually removed it two days ago: https://github.com/ushahidi/Crowdmap-New-UI/commit/f6ce91c62d7f316f11c5e58c1a58f12a7c856658

We may have some issues with our deploy process. I don't see any errors in DeployHQ.

@evansims I'm afraid code on the server is out of sync with what we have on our production branch. Can you think of any recent changes that could have broken this?

**Comment by eyedol** [comment]
Funky. I still see it.

**Comment by eyedol** [comment]
Where can I test the fix? Just to be sure it's gone.

**Comment by brianherbert** [comment]
It's just an HTML tag so I don't think you need to test a fix. I'm more concerned about the fact that we deployed this change but it didn't go away. I think we may need to verify that all of the files we have up on the site match our production branch in github.

**Comment by evansims** [comment]
Nope, no configuration changes in weeks. DeployHQ says we're up to date, but the header file is definitely out of date on production (just took a look.) I recall us having this issue with the DeployHQ process at least once with Classic as well.

Maybe try a faux edit on the file to force a redeploy?

Sidenode: DeployHQ really needs a manual 'full redeploy' option.

**Comment by brianherbert** [comment]
I'll do a redeploy here in a minute and get back.

**Comment by evansims** [comment]
![screen shot 2013-05-15 at 1 05 49 am](https://f.cloud.github.com/assets/3093/505433/8f8e1a74-bd25-11e2-8774-94c872131585.png)

![](https://dl.dropboxusercontent.com/u/23890/sobbing.gif)

**Comment by brianherbert** [comment]
Hah! But the little delivery man looks so happy!

**Comment by eyedol** [comment]
LOL

**Comment by brianherbert** [comment]
I have a deploy pending ATM.

**Comment by brianherbert** [comment]
Looks like that did the trick. Odd.
