### ISSUE TITLE
Landed back at unedited post after saving

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/crowdmap-issues#181]
1. Went to this post: https://crowdmap.com/post/1054/
2. Edited the description and location
3. Saved

Result: back at unedited post.
If I reload the edits show up.

Expected result: after saving the post should reload and show the edited version

**Comment by evansims** [comment]
Note: After editing posts we need to use root.cacheSafeReload() to ensure the browser doesn't render the old cached copy.

**Comment by brianherbert** [comment]
Thanks Evan, noted.

Currently the behavior is to drop you on the individual post page but it takes a few seconds (depending on connection) to get the person over to that page. A better solution is swapping out the actual post in the post listing with the new one.

**Comment by evansims** [comment]
Added workaround for browser caching page state with https://github.com/ushahidi/Crowdmap-New-UI/commit/8ea932bcbf1bb684e98890b61c869d427f78524f. Pushing to production shortly.
