### ISSUE TITLE
Support personalized and global post streams. #design #ux

### ISSUE THREAD

**Issue by evansims** [ushahidi/crowdmap-issues#19]
Right not everything just lands on your homepage in one stream. We need to support two different streams: personalized (just those users and maps you follow) and global (everyone).

![Screenshot_4_13_13_3_59_PM](https://f.cloud.github.com/assets/3093/377114/3536f228-a47d-11e2-9006-e36da25e5889.png)

I think as far as the design goes, a toggle element not unlike an iOS-esque switch would be great, but I'll leave this to the designer folk to decide.

![ios6donotdisturb-580-100019518-medium](https://f.cloud.github.com/assets/3093/377117/9447b068-a47d-11e2-91c0-28d64a47dac1.png)
Stream: [Personal / Global]

**Comment by evansims** [comment]
Here's how **App.net** handles it:

![Screenshot_4_13_13_4_19_PM](https://f.cloud.github.com/assets/3093/377132/cbed59d0-a47f-11e2-82aa-9a1e2531d58c.png)

**Twitter** used to have a 'Global' section, but they appear to have removed it. It's still accessible via the API, but no their frontends.

**Google+** takes a different approach; they have an 'Explore' section that includes trending topics, popular posts (based, I presume, a weighted score including views, comments and +1s). "What's hot" posts also sometimes surface into your personalized stream there, which I really dislike, but you can control the frequency of this using that slider in the upper right hand corner of the screen.

![Screenshot_4_13_13_4_21_PM](https://f.cloud.github.com/assets/3093/377137/4fd9e326-a480-11e2-9611-5312eb3ef7b6.png)

**Comment by brianherbert** [comment]
Agreed. I think we haven't returned a personal stream yet since the site doesn't have a critical mass of usage.

**Comment by evansims** [comment]
Yeah, I think it's all global right now. I had done some prototyping on personal vs global streaming with my work on the https://api.crowdmap.com/v1/posts/stream/?apikey=godmode endpoint, but that was awhile ago and, as I see now, completely broken. :) Low priority stuff for now, but something we should be meditating on for the future.

**Comment by brianherbert** [comment]
I'm working on this now.

**Comment by brianherbert** [comment]
This is complete. I'm going to close this and assume anything that comes in related to this is a new feature request or a bug.
