### ISSUE TITLE
Current users not being forwarded to complete signup

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#190]
The login form just spins. Working on this right now.

Pinging @heatherleson since this might be an issue people are experiencing.

**Comment by brianherbert** [comment]
This should be cleared up. Heather, if you had people recently with login issues with a classic account trying to login to new, let me know.

**Comment by heatherleson** [comment]
Can we set up a time with a number of super users to test this item when you are online? (see issues noted on skype earlier today).

**Comment by brianherbert** [comment]
I'm not sure that's necessary. I've confirmed the bug is fixed but if it comes up still, please let me know.
