### ISSUE TITLE
Notification on users following other users

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#194]
This is debatable if we want to do this or not. Twitter does.

We could notify users when they have a new follower. This would serve as a reminder that a users posts are being seen. For very popular users, it may be nice to have an option to limit notifications ( Issue #193 )

**Comment by heatherleson** [comment]
All notifications to users for their posts, comments or to their collaborators should be opt in or out in the settings.

**Comment by brianherbert** [comment]
This is for email notification

**Comment by evansims** [comment]
We already have email notifications of new followers,  though. You (Brian) and I don't see them because everyone is setup to silently follow us at sign up.

**Comment by brianherbert** [comment]
Oh, nice. ;)
