### ISSUE TITLE
Sometimes images aren't displayed

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#196]
Images just have a blank placeholder, no errors in console. This only seems to happen on the post listing pages on maps.

Tested on FF, Chrome, Safari and iOS.

https://sweetmaps.crowdmap.com

![screen shot 2013-05-23 at 1 27 58 pm](https://f.cloud.github.com/assets/106068/552668/37265ee0-c361-11e2-9432-6d8b9876b656.png)

![screen shot 2013-05-23 at 1 28 58 pm](https://f.cloud.github.com/assets/106068/552671/53046b16-c361-11e2-8b5c-4059d4ce577d.png)

However, some load like this one:

![screen shot 2013-05-23 at 1 29 41 pm](https://f.cloud.github.com/assets/106068/552673/6c02e00c-c361-11e2-9920-0c424b4c9eff.png)

**Comment by brianherbert** [comment]
Here's the HTML it's producing for an image:

``` HTML
<div class="ux-image ondemand" onclick="window.location='/post/1142/';" style="cursor: pointer; padding-bottom: 63.3495%;" height="522" width="824" data-breakpoint-high="1224" data-breakpoint="" data-src-high="https://b25c7ada827abcbc0630-5454a9e6f7100566866dd221e5013c79.ssl.cf2.rackcdn.com/519736104b6871.58188194_o.jpg" data-src-medium="https://b25c7ada827abcbc0630-5454a9e6f7100566866dd221e5013c79.ssl.cf2.rackcdn.com/519736104b6871.58188194_l.jpg" data-src="https://b25c7ada827abcbc0630-5454a9e6f7100566866dd221e5013c79.ssl.cf2.rackcdn.com/519736104b6871.58188194_s.jpg" data-ondemand-state="ready" data-loaded="true"> … </div>
```

**Comment by evansims** [comment]
Hm, it's that empty breakpoint attribute that'd be breaking it. Wonder why that isn't getting returned by the API. I'll check into it, thanks.

**Comment by evansims** [comment]
Hah, probably because I wasn't requesting all the necessary fields in our API call! Fix incoming.

**Comment by evansims** [comment]
Resolved with https://github.com/ushahidi/Crowdmap-New-UI/commit/07c5ca18b72c44ed19b2e87d317db13d8b436c20
