### ISSUE TITLE
Switch out "latest posts" menu text for a webfont icon #ux #design

### ISSUE THREAD

**Issue by evansims** [ushahidi/crowdmap-issues#20]
I'd like to see us swap out the "Latest Posts" string we currently use in the header:

![Screenshot_4_13_13_3_59_PM](https://f.cloud.github.com/assets/3093/377114/3536f228-a47d-11e2-9006-e36da25e5889.png)

For something more likeweight like a simple icon with the down arrow (menu indicator) next to it. We could continue to use full text inside the menu itself, though we'd want to show the icons next to those string options to communicate what the layout looks like.

Icon examples for summary and photos views:
![Screenshot_4_13_13_4_06_PM-2](https://f.cloud.github.com/assets/3093/377120/f84acfd2-a47d-11e2-86bb-935f59690bec.png)
(Icons taken from [Font Awesome](http://fortawesome.github.io/Font-Awesome/))

Thoughts?

**Comment by evansims** [comment]
Implemented new filtering header.

**Comment by brianherbert** [comment]
I totally missed this issue before, sorry I never gave input!
