### ISSUE TITLE
Maps and editing

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#201]
Added a post, connected it to the "whereisheather" map, clicked save. Created "globalanimals" map. 

Edited the original elephant post to move tags to the end of the post and to add Map share to "globalanimals", clicked save. The post is not on both maps. So, it looks like adding a post to a map after the fact does not work. 

https://crowdmap.com/post/1395/
http://dl.dropbox.com/u/34693557/Screenshots/ej.png

**Comment by brianherbert** [comment]
Confirmed. Thanks for the report!

**Comment by brianherbert** [comment]
Fixed. Closing.
