### ISSUE TITLE
Maps Listing Discoverability

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#204]
There is only one page of "global maps". I noticed that on it, "Sweet maps" is missing
https://crowdmap.com/maps/

Also, the list is not in alphabetical order. It will be unwieldly soon.

There are already duplicates. This might be something to surface when creating a map. Show "similar maps"

**Comment by brianherbert** [comment]
I've updated the title of this issue. This is known but we don't have an issue in Github for it. We need to build out the discoverability features in the maps listing section utilizing the map tags, popularity, etc.

Currently this lists maps in order of creation with no pagination. It's a band-aid for now.

**Comment by evansims** [comment]
This process has gotten a lot of love in the forthcoming UI update, so going to close this for now. There are still improvements we could make to discoverability that we should consider, but let's break those up into individual issues we can attack down the road.
