### ISSUE TITLE
Collaborators

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#205]
I'm having a time 1. finding collaborators and 2. trying to share posts/maps.

The collaboration workflow needs some secret sauce. I sent out a mailing to some 1xxx beta signups. How many are signed in and have created posts? How can I easily find and connect to them? I am now simply monitoring 'latest posts'

**Comment by brianherbert** [comment]
okay, this issue is asking for a lot of different things.
1. Finding Collaborators UI
2. Sharing posts UI
3. Sharing maps UI
4. Collaborator workflow
5. User signup statistics
6. User search / findability
7. Post search / findability

What is the one thing you need?

**Comment by heatherleson** [comment]
Hi Brian
Each of these are part of the experience I am suggesting. I've posted previous issues about # 2 and # 3. Basically, I just want to find and collaborate

**Comment by evansims** [comment]
Closing as I think this has been more or less addressed via other tickets
