### ISSUE TITLE
Markdown Cheatsheet

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#207]
We need something to show users how to format markup in their post using markdown.

**Comment by brianherbert** [comment]
I have added a **very** basic table showing bold, italics and bold/italics markdown options. There's a link to Daring Fireball to get more into depth on it. I know we can do better but I think this is enough of a start to close this ticket.

![screen shot 2013-05-27 at 2 51 21 pm](https://f.cloud.github.com/assets/106068/566537/ac7d06ac-c691-11e2-8a0e-c320671240bd.png)

If we need a more advanced cheat sheet or change the UI, we may want to open another ticket. If we need to make minor adjustments, let's reopen this one.

**Comment by heatherleson** [comment]
updated docs - https://wiki.ushahidi.com/display/WIKI/Crowdmap+-+Your+Posts
