### ISSUE TITLE
Global posts - see all

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#209]
Make it easier to see all the posts on crowdmap. Currently, it is an obscure: http://dl.dropbox.com/u/34693557/Screenshots/eo.png

The workflow to see: all posts, all maps or only the maps/posts you follow needs to be clearer. Either add tooltips or something so that discoverability is easier.

**Comment by evansims** [comment]
Thanks Heather. I've implemented a new filtering header for post streams. It includes icons grouped by filter type (global/following, posts/photos) and tooltips to describe their purpose.

![screen shot 2013-05-28 at 9 19 29 pm](https://f.cloud.github.com/assets/3093/576505/40b2201c-c806-11e2-93a4-09d31ff7c414.png)

**Comment by heatherleson** [comment]
Thanks! Updated docs - https://wiki.ushahidi.com/display/WIKI/Crowdmap+-+Discover+Views
