### ISSUE TITLE
Remove unnecessary "about" from timeago output. #design #code

### ISSUE THREAD

**Issue by evansims** [ushahidi/crowdmap-issues#21]
Adds unnecessary bulk to post headers

![Screenshot_4_13_13_4_09_PM-2](https://f.cloud.github.com/assets/3093/377124/94eb7bde-a47e-11e2-946f-5243ff320373.png)

**Comment by brianherbert** [comment]
I did this for English. We probably don't want to jump into the localizations on this one. I also shortened a string.
