### ISSUE TITLE
User search styling way off

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#210]
Searching for users works, but the avatars are blown up. See screenshot.

![screen shot 2013-05-27 at 11 59 46 pm](https://f.cloud.github.com/assets/106068/568565/35f87780-c6de-11e2-962a-fcde41808014.png)

**Comment by evansims** [comment]
Resolved with https://github.com/ushahidi/Crowdmap-New-UI/commit/2478d09df3115375f1d0b708018d9085ecbb1351
