### ISSUE TITLE
Remove "advanced options" when not searching for posts

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#211]
We can reintroduce it but only when we have relevant advanced search filters for maps and people. In the mean time, limiting a search for people by post IDs won't do anything.

![screen shot 2013-05-28 at 12 01 16 am](https://f.cloud.github.com/assets/106068/568569/5c50c4b4-c6de-11e2-901a-70f5e8fb80f8.png)

**Comment by evansims** [comment]
Resolved with https://github.com/ushahidi/Crowdmap-New-UI/commit/2478d09df3115375f1d0b708018d9085ecbb1351
