### ISSUE TITLE
Increase pagination limit for pulling user details

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#213]
Making tons of requests when trying to create a post. I know why we're doing this but maybe we can return 50 results instead of 20 per request to cut down on the number of calls we have to make.

![screen shot 2013-05-28 at 5 01 47 pm](https://f.cloud.github.com/assets/106068/571124/01d6f67c-c76d-11e2-8e8d-f4d0b827a994.png)

**Comment by evansims** [comment]
Yeah, that's a bit nuts. I went ahead and knocked this up to 50 results per request.

**Comment by brianherbert** [comment]
:dancers:
