### ISSUE TITLE
Map Listing doesn't show all followed maps

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#217]
@middle8media followed https://crowdmap.com/map/awesomecoffee/ but it's not showing up in the maps followed listing.

http://cl.ly/PHx5/Screen%20Shot%202013-05-29%20at%203.02.48%20PM.png

**Comment by sethburtonhall** [comment]
With WhiteAfrican as well. Same issue I assume.

**Comment by brianherbert** [comment]
Not to take this off on a tangent but you bring up an issue I don't think we handled with map listing pages. You can follow both users (whose profiles are "maps" but not actual maps) and maps (the real thing). I'm wondering if people follow users if they expect the maps listing page to list them as well.

Brandon had them mixed in his original markup but the API just doesn't work that way. We have to make two different requests to get users being followed and another request to get the maps. Mixing those with different data structures would be too complicated. Something to chew on.

**Comment by brianherbert** [comment]
Fixed a typo that was causing this. Should be cleared up now.

Still thinking about the user profile (maps) versus maps confusion though.

Closing.

**Comment by sethburtonhall** [comment]
Let's chat more about this on monday.
