### ISSUE TITLE
Create post pulls user details at the same endpoints hundreds of times. Possible browser lock up.

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#219]
This is similar to #213 but not directly related. This is nearly crashing my browser when I try to create a post. Judging by the offset, each request is being made 15 or more times.

![screen shot 2013-05-30 at 11 47 40 am](https://f.cloud.github.com/assets/106068/582984/737cca7e-c8d3-11e2-86da-67528ba4c91b.png)

**Comment by evansims** [comment]
Sigh, just when I think I have this thing working right. I'll look into it.

**Comment by brianherbert** [comment]
@evansims I took a crack at this with https://github.com/ushahidi/Crowdmap-New-UI/blob/master/assets/js/crowdmap.typeahead.js#L91-L98 but I'm not sure it's correct. I see there's a globalTypeaheadCache which I'm assuming should be holding the necessary data for the other textareas that are supported by typeahead.

Any chance you could take a look before I break something unintentionally?

**Comment by evansims** [comment]
Yeah don't do that. There's logic already to avoid this built in, but it's apparently broken. I'll fix.

**Comment by brianherbert** [comment]
Suspicion verified, hence my stopping ;)

**Comment by evansims** [comment]
All fixed, sorry about that. I broke it last night when I added stream-in support for new suggestions as the Ajax results come in. :)

**Comment by brianherbert** [comment]
Hakuna matata! :bow:
