### ISSUE TITLE
allow clickable elements in subtitle

### ISSUE THREAD

**Issue by sethburtonhall** [ushahidi/crowdmap-issues#221]
For example, the link below the title of my Coworking Spaces Map

https://crowdmap.com/map/coworkingspaces

Adding MD support could be a good solution.

**Comment by evansims** [comment]
Good suggestion, thanks. I've updated user and map descriptions to support links, usernames and hashtags. MD support would be good but until we fix some issues with that this is the next best thing.

**Comment by sethburtonhall** [comment]
Awesome. Thanks.

I wonder if there is a way to automatically link @usernames to Twitter?

Maybe offer some micro text underneath the "Short Bio" section saying

"@usernames will automatically link to Twitter"

or something like that.

Unless this conflicts with Crowdmaps @usernames

**Comment by evansims** [comment]
I agree that would be nice, but my concerns are:
1. We would need to then support that in posts and comments to maintain uniformity. 
2. I exist as @evansims on both CM and Twitter -  how do you choose to link to me there vs here?
3. We could check if the @ username is registered on CM and default to a Twitter link if it isn't,  but what if the @'d username is registered later?
4. We currently process @'s and #'s dynamically on the client side at display time, so we can't store and recall what the intent of a @ was. We'd have to convert Twitter @ references into URLs and insert those instead. Which is an option, but would add complexity to what should be a frictionless experience.

I think we're best off maintaining the current setup and just let folks write out the URL to Twitter accounts to link them.

**Comment by sethburtonhall** [comment]
Yep. Sounds about right.

**Comment by evansims** [comment]
Cool. Thanks again for the suggestions! Keep 'em coming. :)
