### ISSUE TITLE
Links in emails not working

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#224]
Emails link through email.crowdmap.com, which doesn't seem to be responding.

Sent a support request to Sendgrid since they modify links.

**Comment by evansims** [comment]
I made a tweak to the Send Grid settings that may help with this. When we upgraded we got access to a few new options, several of which default to sending mail from subdomains we don't use. I've switched them to use the root domain. I don't know if this will fix the problem, though.

**Comment by brianherbert** [comment]
I have an open ticket with them, I'll let them know.

**Comment by brianherbert** [comment]
Unless SendGrid gets it's act together before DeployHQ is back up (and I'm online), this ticket will be converted to switching to https://postmarkapp.com. I already have an account set up there and will be using it for BRCK related email.

Added bonus, Postmark will allow us to do inbound email easily.

**Comment by brianherbert** [comment]
Made the switch to Postmark. Closing.
