### ISSUE TITLE
Media uploads not working

### ISSUE THREAD

**Issue by evansims** [ushahidi/crowdmap-issues#229]
Might be a Rackspace outage. Investigating.

**Comment by evansims** [comment]
Transitioned ticket from update to #149.

Further testing is showing the uploads do work eventually, but are taking a very long time.

**Comment by evansims** [comment]
Seems to be getting better here. @heatherleson Same for you?

**Comment by heatherleson** [comment]
will test ; )

**Comment by heatherleson** [comment]
Desktop - easy, fast - https://crowdmap.com/post/2230/another-pic-from-the-ushahidi-istanbul-meetup-april

**Comment by evansims** [comment]
Appears to be working OK now. Must have been a Rackspace network hiccup.
