### ISSUE TITLE
Don't remove whitespace on save

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/crowdmap-issues#230]
After the change to markdown handling my whitespace got dropped on save

```
Test post *bold* and _stuff_
http://gh.robbiemackay.com
```

became

```
Test post _bold_ and _stuff_[gh.robbiemackay.com](http://gh.robbiemackay.com)
```

I know the single new line is ignored by markdown but its a pain to have it removed.. especially if I then go back to edit, having realised I got bold wrong and needed another new lines.

**Comment by evansims** [comment]
Hm, we support GFM style for line breaks so the newline shouldn't have gotten removed. I'll check into this, thanks!
