### ISSUE TITLE
fix icon size and spacing on "Create Map" button

### ISSUE THREAD

**Issue by sethburtonhall** [ushahidi/crowdmap-issues#234]
http://cl.ly/PUYW

**Comment by evansims** [comment]
Good call. Going to append this to fix as well, since they're related:

![capture](https://f.cloud.github.com/assets/3093/627878/77ab3bd6-d061-11e2-9752-945e1f62fbf1.png)

**Comment by sethburtonhall** [comment]
yes, easy fix.

**Comment by evansims** [comment]
Fixed (finally)

**Comment by sethburtonhall** [comment]
Awesome!

Unrelated: sort of:

not sure if you know this or not, but FontAwesome has a Bootstrap CDN for painless updating.

http://fortawesome.github.io/Font-Awesome/get-started/

**Comment by evansims** [comment]
Nice! We don't use Font Awesome at the moment, but I'd like to transition us to it soon. I use it a lot in other projects, and it's pretty... well, awesome. :)
