### ISSUE TITLE
Email forwards - signature and subject lines

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#241]
The Email pun forwards: 
When you send an email from your mailbox, it includes the signature and subject line. Can it strip this? I edited the post
https://crowdmap.com/post/4158/?r=9406
http://dl.dropbox.com/u/34693557/Screenshots/fc.png

**Comment by brianherbert** [comment]
I've done a little research this morning, and apparently it's almost impossible to detect a signature block to remove it unless it's using the standard format with a "--" separating the message body from the signature.
