### ISSUE TITLE
comments and comment window not closing

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#243]
Added comment via android /create page
Window does not close
Thought it did not close.
tried again.
Clicked done again and it closed

screenshot won't post via phone . Added
![comments](https://f.cloud.github.com/assets/1216707/644458/602391e6-d38d-11e2-8fc2-7e95e6d5b72d.png)

**Comment by brianherbert** [comment]
![don_e8fc6b_336231](https://f.cloud.github.com/assets/106068/666425/f675b354-d7c5-11e2-9253-7bc6f55e4a31.jpg)
