### ISSUE TITLE
Can't locate post on 2nd attempt to create

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/crowdmap-issues#245]
So here's the steps
1. Went to https://crowdmap.com/map/coworkingspaces
2. Click 'Create post'
3. Add text
4. Add location
5. Publish
6. Click 'create post' again
7. Add some text
8. Try to add location.. but it seems to get stuck with the previous location I posted selected..
![screen shot 2013-06-11 at 1 51 31 pm](https://f.cloud.github.com/assets/7965/635121/c1ea5900-d239-11e2-8c08-4ab52c0e3406.png)

**Comment by evansims** [comment]
Confirmed fixed in forthcoming UI update.
