### ISSUE TITLE
Account activation via email

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#247]
Since a few spam accounts have cropped up, I think we should revisit how we will handle account activation via email. I'm of the opinion that we don't want to keep people from diving right in and doing an email dance but I do think we need to make certain people are who they say they are. Perhaps we have a mechanism to allow them to go without activation for a set period of time (1 hour?) before disabling the account to wait for that activation?

Previously discussed in #125

**Comment by evansims** [comment]
Personally, I don't think there's much harm in requiring newly registered users to activate before posting. I realize it's a speed-bump in using the service, but they're already in the "sign up mindset" so it's probably the best possible time to get them to do it. And, of course, they can always post anonymously (though I suspect spam attacks from that front are inevitable too.)

My concern with the hour later approach is most spam attacks, including the one's we've seen, only post one or two things within a very brief period after signing up, then never revisit the account. I'm not sure locking them out after an hour would do much good in the long run.

**Comment by brianherbert** [comment]
Yeah, I think that's okay to require it up front, just trying to think of any way to reduce friction.

**Comment by brianherbert** [comment]
I believe email activation has since been implemented. Closing.

**Comment by brianherbert** [comment]
.... to clarify, it hasn't been fully implemented but this ticket is stale so keeping it closed.
