### ISSUE TITLE
Instagram mysteriously stopped working after it was working

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#248]
WTF.

Instagram posts don't auto-post anymore.

**Comment by evansims** [comment]
Could I have broke something the other day when I made this tweak? https://github.com/ushahidi/Crowdmap-New/commit/8f7f1b0980662893e4d0c5075d1803dfdf29ae81

**Comment by brianherbert** [comment]
Should be back up and running....... for now.

Closing.

**Comment by evansims** [comment]
![](https://dl.dropboxusercontent.com/u/23890/instagram.gif)

**Comment by brianherbert** [comment]
That gif sums up exactly how I feel about this.
