### ISSUE TITLE
Search Results not pulling full set

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#249]
Search results do not show the full results. 

https://crowdmap.com/search/  (turkey, istanbul)

There were more results than this. is it not showing pagination or were older results removed?

**Comment by brianherbert** [comment]
Are you searching for keyword text or a location?

**Comment by evansims** [comment]
Pagination is still lacking from search results. I'll try to get that online the first of this week.

**Comment by heatherleson** [comment]
I searched "turkey" and "istanbul" as text

**Comment by brianherbert** [comment]
Are you searching for those as keywords or as a location?

**Comment by heatherleson** [comment]
keywords = text = "turkey" and "istanbul"

**Comment by brianherbert** [comment]
okay, so you were not searching for posts inside turkey or instanbul, only posts that had those words in the message body. Thanks for clarifying!
