### ISSUE TITLE
Search results strip photos

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#250]
Searched "Istanbul" to see all the results. 

In the Search results page, my photos were stripped:
http://dl.dropbox.com/u/34693557/Screenshots/ff.png

If you go to the original posts, the pictures display:

https://crowdmap.com/post/2230/
https://crowdmap.com/post/2218/

**Comment by brianherbert** [comment]
This is currently expected behavior as a cheap "compact" view. I created #251 just now to cover this. Thanks :+1:
