### ISSUE TITLE
Add oembed support to the API

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#258]
oembed will allow us to work with services that embed content in the standard oembed format.

**Comment by heatherleson** [comment]
Another example 
http://dl.dropbox.com/u/34693557/Screenshots/ft.png
https://www.facebook.com/ushahidi/posts/584698341550204

**Comment by brianherbert** [comment]
Moving this issue to #271 since oembed is in. I should have closed this the other day ;)
