### ISSUE TITLE
Automatic posts to twitter end up tweeting from Brian's twitter account. 

### ISSUE THREAD

**Issue by aoduor** [ushahidi/crowdmap-issues#259]
Hehehehehe.

Angie creates post on new crowdmap, and opts to auto post to her twitter timeline too :).

https://crowdmap.com/post/4466/rain-really-also-whoop-whoop-tweeting-from-my-crowdmap

Result: https://twitter.com/brianherbert/status/345561453027274753

![screenshot](http://i.imgur.com/9Tx25eR.png)

:D

**Comment by brianherbert** [comment]
Agh!

**Comment by brianherbert** [comment]
This is fixed. Thank you @aoduor for not posting anything inappropriate ;)
