### ISSUE TITLE
Facebook + Post sharing = love

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#261]
Make it possible for individual crowdmap posts to show photos and content on Facebook. 

Ushahidi page:
https://www.facebook.com/ushahidi?fref=ts

What you see: 
http://dl.dropbox.com/u/34693557/Screenshots/fj.png

It would be better for community/interaction to be able to post the individual maps/posts and the associated rich media content

**Comment by brianherbert** [comment]
Duplicate of #164 

I think this may be related to an issue I'm having with #258 not working on production, also.

Closing.
