### ISSUE TITLE
Gatekeeper flips out when cookies are disabled

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#262]
When you disable cookies and hit crowdmap.com, it looks like it continually reloads itself. Expected behavior should be to send you to the default server set in the gatekeeper script.

Looking into it now.

**Comment by evansims** [comment]
This is a toughie. If cookies are disabled then, of course, Gatekeeper can't set anything; not even a marker to let us know it's our first attempt at hitting Gatekeeper and falling back. Nginx has no way of telling if cookies are disabled, either. I'm not sure there's really a fix for this situation.

**Comment by brianherbert** [comment]
Yeah, I was thinking about some kind of dance adding params to the URL to test for cookies but that's a mess.

I think since I added /post to auto hit the new server, we should be okay. I was primarily concerned about services that try and pull our oembed data programatically (ie Embedly).

Closing.
