### ISSUE TITLE
Anonymous users shouldn't be able to like posts

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#265]
The like functionality shouldn't be clickable (but should be viewable) for anonymous users. I see an anonymous user "liked" my post.

The broken image in this screenshot is an anonymous user.

![screen shot 2013-06-18 at 10 19 54 am](https://f.cloud.github.com/assets/106068/666062/7fba4280-d7b5-11e2-945f-53092fc1c831.png)

**Comment by evansims** [comment]
I think that might actually be a user who hasn't set their avatar and has no gravatar. That was a quick and dirty hack and it doesn't properly resolve to the default avatar in those cases. I need to fix that. :)

We should pop up a UI prompt for registering or logging in or something when Anons hit that I guess, though.

**Comment by evansims** [comment]
Sorry, I should have checked before I replied. You are correct, Anons were able to like. I've fixed this on the server side (push to production pending.) Will make some UI sided tweaks to make this rule obvious.
