### ISSUE TITLE
Leverage API for inline post translations

### ISSUE THREAD

**Issue by evansims** [ushahidi/crowdmap-issues#269]
We should investigate leveraging the [Google Translate API](http://code.google.com/apis/language/translate/overview.html) to offer rough, inline translations of posts.
- We could begin using the API to determine what language a post is written in at post time.
- Visitors could hit a "Translate" option in the cog menu to see a list of possible languages to translate the post into.
- We would hit the Google Translate API, then replace the post body inline with the resulting translation.

I realize this sort of translation is very inaccurate, but I think it might be better than nothing. Would this be cost prohibitive? (I'm open to other APIs, of course; the Google Translate API is the only one I'm familiar with off hand.)

Thoughts @brianherbert @heatherleson @aoduor

**Comment by brianherbert** [comment]
I was looking into this today (weird).  

Actually, I've poked around with machine translation APIs quite a bit and as far as I know, there are no free alternatives, especially with the breadth of languages that Google offers.

We'll have to look into pricing to see about this. It's something Swift may be able to benefit from as well.

**Comment by evansims** [comment]
Awesome! I was just looking at [this post](https://crowdmap.com/post/4675/) and really wishing I could seamlessly see the text in english. Would be a huge addition. Anyway, yeah. Let's investigate.

**Comment by brianherbert** [comment]
Looks like it's $20 for 1M characters. It sounds like a lot of characters but I'm curious to see how that would play out.  

They also have the language detection API for the same price. I would love to tag posts with a language so we can search/filter by language.
