### ISSUE TITLE
Twitter oEmbed introduces many instances of widget.js

### ISSUE THREAD

**Issue by evansims** [ushahidi/crowdmap-issues#270]
Low priority, but there is some fat we can trim here. Twitter has [some tips](https://dev.twitter.com/docs/embedded-tweets) — such as including a ?omit_script param — to avoid duplicate JS includes, but we might be able to do it more effectively on the client side by simply parsing our API responses and setting a flag, and scraping out the include before inserting into the DOM.

Will investigate.

![screen shot 2013-06-18 at 1 41 07 am](https://f.cloud.github.com/assets/3093/667008/1c2e88ac-d7e2-11e2-9879-4d0073dcf665.png)

**Comment by brianherbert** [comment]
We can include the widget.js ourselves and tell the API to not include it when we pull the embed code. That's in their docs.

**Comment by evansims** [comment]
True, but I'd hate to include that on every page load if we aren't going to necessarily need it every time. I suppose we could just sniff for Twitter's styling in the externals responses and include it on the fly when needed. That could work.

**Comment by brianherbert** [comment]
Can't we use requirejs to include it when we embed something using twitter?

**Comment by evansims** [comment]
We can, but unless a script is structured as an asynchronous module, RequireJS will just keep requiring it over and over again. So we'll just need to keep a flag in the globals to mark that we've already done it.

**Comment by brianherbert** [comment]
I'm curious how often they update it, if we could host a local copy of the file (periodically update it on a cron?) and wrap it with the necessary "define" structure. Overkill?

**Comment by evansims** [comment]
Fixed! We now manage the inclusion of the JS internally (using the CrowdmapUI.parseTweets method.) This turned out to be a massive performance improvement for WebKit-based browsers. Not sure what they're doing in that JS, but... damn!
