### ISSUE TITLE
Facebook OpenGraph Description Incorrect

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#271]
Facebook OG tag is sometimes pulling in wrong description. Could be an inescaped description?

![ft](https://f.cloud.github.com/assets/106068/672389/c9cd1fae-d87e-11e2-9980-a9a59edf3e20.png)

**Comment by brianherbert** [comment]
Our canonical URLs are incorrect and there are issues with redirection for the post at https://crowdmap.com/post/4669

https://developers.facebook.com/tools/debug/og/object?q=https%3A%2F%2Fcrowdmap.com%2Fpost%2F4669
![https_crowdmap com_post_4669- facebook developers_20130619-102723](https://f.cloud.github.com/assets/106068/672411/6a574e2c-d87f-11e2-85ea-34a352241c4b.png)

**Comment by evansims** [comment]
I see the problem; if there's no text body, as is the case in that tweet-only post, there's no post stub. No post stub means the canonical post formatting is incorrect. Fixing.

**Comment by brianherbert** [comment]
This could happen in posts with no message body and only external attachments, photos, etc, correct? Should we have a default stub when there is no text to stub-ize?
