### ISSUE TITLE
Digest Email

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#272]
Dependent on #193 

Once we have notification options, have a weekly digest email detailing activity relevant to users like popular posts by people they follow, interesting content on Crowdmap, traffic to their maps, etc.

Pinging @heatherleson since she probed us to have this issue up :+1:

**Comment by evansims** [comment]
I believe this was implemented some time ago, or at least the mechanism for people to sign up was. Feel free to re-open if I am incorrect.
