### ISSUE TITLE
Crowdmap and Mac Commands - needs work

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#276]
Tried to make a screen smaller (shift - and the "-" sign)> It mucked up the screen - http://dl.dropbox.com/u/34693557/Screenshots/fv.png

Browser - ff
Screen - global search home page
https://crowdmap.com/posts?global=true

**Comment by evansims** [comment]
Hmmm, so the command +/- browser zoom shortcuts - or rather the page zoom functionality attached to those - do appear broken on Firefox for Mac V21. It works fine under Firefox for Windows V21, but is completely broken on Mac. Works fine in Chrome on both platforms.

I just tested this in Firefox for Mac V19 and V20 and it works fine in those versions, so I'd have to chalk this up to a browser bug. I'm trying to search their bug repo to see if it's a known issue but that thing is a disaster zone to say the least.

**Comment by heatherleson** [comment]
ok, I tested again and it worked fine. Closed, I guess

**Comment by evansims** [comment]
That's a weird one. I can't quite explain it, but yeah. Closed for now. :)
