### ISSUE TITLE
Showdown converts URL underscores to italics

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#28]
See screenshot. URL should be: http://www.reddit.com/r/MapPorn/comments/1c4xrn/language_diversity_across_torontos_44_wards_based/

![Screen Shot 2013-04-15 at 3 05 46 PM](https://f.cloud.github.com/assets/106068/379295/96cedaee-a592-11e2-85e5-7d1b660d2bd4.png)

**Comment by evansims** [comment]
So this is a good opportunity to bring up something I've been thinking about that would also serve as a workaround for this; I think it would be beneficial for us to implement Bitly's short linking API to replace all links in posts.

This would allow us to protect users from spammers trying to peddle malware (Bitly does a really good job of validating and intercepting evil links as users click through them.) It would also allow us to display short links for mobile users. We could dynamically expand the displayed strings for desktop and tablet users who have the screen real estate to spare.

I've been toying with the API this afternoon to this end, but I thought I'd get your thoughts before I went further with this.

**Comment by brianherbert** [comment]
We have a bitly pro account using http://crwd.mp which at the moment, looks like its not pointing at bitly.  

I'm definitely not opposed to this.

**Comment by evansims** [comment]
Aye, that's the account I've been working with. The DNS is all screwy on it, waiting for my updates to go through.

**Comment by brianherbert** [comment]
I fixed this, but we should still talk about a URL shortener. I'll open a ticket for that.

Closing.
