### ISSUE TITLE
Attaching Post To Multiple Maps

### ISSUE THREAD

**Issue by eyedol** [ushahidi/crowdmap-issues#280]
Crowdmap allows you to attach post to multiple maps when creating the post but upon saving the post, it only selects one. 

See the screenshots below.
**create a post**
![screenshot_2013-06-21-14-30-16](https://f.cloud.github.com/assets/73175/685527/af6353f0-da35-11e2-806f-bc1bc35caaf4.png)

**saved post**
![screenshot_2013-06-21-14-30-36](https://f.cloud.github.com/assets/73175/685529/d2fb8684-da35-11e2-8f4e-cd1a6bd9c46c.png)

**Comment by eyedol** [comment]
I was selecting a map I follow. Perhaps I'm not allowed to contribute?

**Comment by brianherbert** [comment]
If a map is set to require approval, then it won't be apparent that it has been attached. We need to improve the UX around this.

**Comment by eyedol** [comment]
Oh I see. I guess, the post is in moderation queue then. I re-tagged the post as `enhancement` instead of `bug`

**Comment by evansims** [comment]
Confirmed fixed in forthcoming UI update.
