### ISSUE TITLE
Windows Phone 7.5 Support

### ISSUE THREAD

**Issue by evansims** [ushahidi/crowdmap-issues#281]
Looking at client-side error reports coming in, it appears we might have a compatibility problem with Internet Explorer in Windows Phone 7.5 (perhaps other versions as well.) Will need to get a emulated environment going to confirm and fix.

**Comment by evansims** [comment]
I'm a bit stuck on fixing this. None of my machines have a processor that supports the virtualization feature Hyper-V requires to run, so I can't use the WP 7.5 or 8 Phone Emulators.

**Comment by brianherbert** [comment]
Looks like you need to just sell your phones on Gazelle and buy a windows phone. Sucks to be you.

**Comment by evansims** [comment]
![](https://dl.dropboxusercontent.com/u/23890/slap.gif)

**Comment by brianherbert** [comment]
I'll pretend I'm not Joffrey in that gif :bear:

**Comment by evansims** [comment]
Or, in another context, I'm Joffrey and Microsoft is Tyrion softly informing me they don't want me to build for their platform. Ever. It's an interpretive gif!

**Comment by evansims** [comment]
Giving up on this one. Sorry, MS fans.
