### ISSUE TITLE
Store Instagram Images Locally

### ISSUE THREAD

**Issue by evansims** [ushahidi/crowdmap-issues#283]
I've noticed that Instagram's AWS mirror is occasionally reporting our network requests as forbidden.

Not sure why (maybe we're hitting referrer access limits?) but it might be beneficial for us to store the Instagram images locally in our own media collection to avoid this, but more importantly so we can apply our sizing and mobile optimizations to those images.

![awsdenied](https://f.cloud.github.com/assets/3093/699795/bde5f594-dd29-11e2-941a-3b5d2bf397ce.png)

![awsdenied2](https://f.cloud.github.com/assets/3093/699796/beabad02-dd29-11e2-9f72-bc17ffa4afa7.png)

Any thoughts or opinions on this?

**Comment by brianherbert** [comment]
I'm down with that.

**Comment by evansims** [comment]
Just to update, I'm 99% done with this. I'll put it into production tomorrow when I can be around to monitor it for bugs.

**Comment by brianherbert** [comment]
Sounds good. Once this is in I'll fix the misbehaving auto-post by Instagram tag for individual maps functionality using your method of saving photos.

**Comment by evansims** [comment]
This has been implemented. (Like a boss.)

![](https://dl.dropboxusercontent.com/u/23890/gandalfrock.gif)
