### ISSUE TITLE
Pulling retweets into crowdmap is confusing.

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/crowdmap-issues#288]
Got confused when Seth's twitter post came through attached to my account https://crowdmap.com/post/5074/ 
Could we have an option to include retweets or not?? Or maybe something to make it more obvious? (more options is probably not better)

**Comment by brianherbert** [comment]
It's definitely easy to identify a RT in Twitter. We're going to have to figure out how best to handle "sub"-options like this in the UI since our current design only gives us the ability to show everything on one page. Nothing we can't tackle though.

**Comment by evansims** [comment]
Going to knock this up to ASAP. The RT flood is kind of getting out of control.
