### ISSUE TITLE
Add to map pop out needs revisited

### ISSUE THREAD

**Issue by evansims** [ushahidi/crowdmap-issues#292]
![screen shot 2013-07-03 at 7 27 46 pm](https://f.cloud.github.com/assets/3093/746934/9cdfe670-e440-11e2-8526-d772365404da.png)

**Comment by brianherbert** [comment]
Quick fix is to add a responsive style to only use one column when the width is small.

**Comment by evansims** [comment]
True; Longer term I was thinking about making it a list view with small thumbnail avatars to the left, and a search field at the top, for when folks end up with dozens or more of maps they're owning or collaborating on

**Comment by brianherbert** [comment]
I've had the same idea so it seems like a good one.

**Comment by evansims** [comment]
Confirmed fixed in forthcoming UI update.
