### ISSUE TITLE
Feature request - RSS feed

### ISSUE THREAD

**Issue by moeden** [ushahidi/crowdmap-issues#297]
I would like to suggest an RSS feed for the new Crowdmap platform. This would provide a stream of images (and related text) which could be 'read' by feed-reading software.

The 'Good Use Case':

I use RSS feeds to filter different channels and package information for the public. I have also seen RSS feeds used to package blog updates as pdf newspapers, and would love to have a 'pdf newspaper' showcasing the month's photos and posts to a wider readership.

At the moment the lack of an RSS feed is the only stumbling block. 

I presume there is wide potential for RSS feeds to be used by other crowdmap users, not least to assist with providing news feeds to Google Currents, Flipboard or other platforms.

Thanks!

**Comment by brianherbert** [comment]
This is something that I would like to implement myself in our API. We already support returning data in XML format so it doesn't seem like it will be too much a stretch to have responses in RSS.

I'm marking this as "soon" so we can try and get it out the door before or shortly after we announce/launch the API.

**Comment by moeden** [comment]
Brian - many thanks for the response, I'm delighted to hear that it'll be looked at soon!
Good luck :)

**Comment by moeden** [comment]
Hi - I thought I'd bump this, and ask if there was any progress? Thanks!

**Comment by brianherbert** [comment]
Thanks for the reminder :+1:

We're currently working on some scaling issues in regards to auto posting content but we can work on this soon after.

**Comment by moeden** [comment]
Thanks very much guys - hugely appreciated :)

**Comment by moeden** [comment]
Hi @brianherbert, how are things going with this suggestion? Hope things are going well overall! 

Thankyou :)

**Comment by brianherbert** [comment]
Thank you for waiting so patiently for this. I've got some very basic RSS support in now. You can test it out with a link like this: https://api.crowdmap.com/v1/maps/sweetmaps/posts/?format=rss

It doesn't support images, author names or locations yet but those would all be nice to add moving forward. You can see maps or posts as RSS feeds.

The maps endpoint is in but it doesn't look like it's working as well as the posts resource: https://api.crowdmap.com/v1/maps/?format=rss

I hope this can help a bit, even though it isn't complete.

Also, this could be considered experimental so expect it to change in the future.

**Comment by evansims** [comment]
Marking Closed/Implemented

**Comment by moeden** [comment]
Thanks all for the info to date. I'm delighted that the RSS feature is now 'live' - what's the http link which would be needed for this site (for example) https://crowdmap.com/map/mozfest2013/ ? I've tried just putting rss at the end - no dice.

**Comment by brianherbert** [comment]
This is currently only available via the API so the URL is going to look a little different. You can see the posts for the mozfest2013 map using this URL: https://api.crowdmap.com/v1/maps/mozfest2013/posts/?format=rss

**Comment by moeden** [comment]
The text works perfectly - is there a simple way to get the images too, or is that too much for the 'api' version? 
(Thx btw :)

**Comment by brianherbert** [comment]
I went ahead and made this a new issue #351
