### ISSUE TITLE
Picking an image in an embed shows multiple images/nonimages (see ss)

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#302]
When I try and page through to select a different image, this happens:

![screen shot 2013-07-26 at 12 48 00 pm](https://f.cloud.github.com/assets/106068/860418/76a5fee6-f5a6-11e2-8c0a-f31d67fa1a59.png)

There should only be one image showing at a time.

**Comment by evansims** [comment]
Fixed
