### ISSUE TITLE
Auto location picker broken

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#303]
I selected "Syria" by searching in the address search for "Syria" then selecting that location in the list of locations. The location saved is the one where I currently am:

![screen shot 2013-07-26 at 12 54 15 pm](https://f.cloud.github.com/assets/106068/860429/30b2e02e-f5a7-11e2-8e7a-48bd1b0fb5a1.png)

**Comment by evansims** [comment]
Confirmed fixed in forthcoming UI update.
