### ISSUE TITLE
Edit Post close icon (X) is showing up when the window isn't modal, it shouldn't be there

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#304]
Since this isn't actually showing up modally, this edit post dialog shouldn't show the close "X".

Besides, it's in the wrong place anyway :wink: 

![screen shot 2013-07-26 at 12 55 52 pm](https://f.cloud.github.com/assets/106068/860434/635fd7f2-f5a7-11e2-94c6-6532756e0722.png)

**Comment by evansims** [comment]
Fixed
