### ISSUE TITLE
Tall Images in Post Modal overlap post options

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#308]
Screenshot:

![screen shot 2013-08-06 at 1 24 03 pm](https://f.cloud.github.com/assets/106068/914870/2632ea48-fe50-11e2-874e-aef28a69a5ab.png)

osx firefox.

**Comment by evansims** [comment]
Forthcoming UI update kills modals. It's not pinin'. It's passed on. This modal is no more! It has ceased to be! It's expired and gone to meet it's maker!
