### ISSUE TITLE
Statistics button doesn't show a modal

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#309]
What does this button do? when you click it, there is no action.

http://dl.dropbox.com/u/34693557/Screenshots/go.png

If it is a new feature, can you please add a wiki how to page to explain it?

**Comment by brianherbert** [comment]
This is the same button that has always been there, except now it says statistics along with the icon.

@evansims and I ran into this issue where the window doesn't pop up yesterday. Looks like it's still an issue.

**Comment by evansims** [comment]
Hm. The server is responding with a 404. I'm knee deep in other work right now, but I'll check this out as soon as I can.

**Comment by evansims** [comment]
Fixed! With the recent API tweaks /follow stopped being an alias for /follows, which broke some things. All patched up now.
