### ISSUE TITLE
Post embeds are sometimes very tall

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#31]
This happens on individual post pages and posts that were just made without refreshing the page. I think there's a javascript function that needs to hit this to resize them properly.

![Screen Shot 2013-04-15 at 3 21 39 PM](https://f.cloud.github.com/assets/106068/379340/c4f8c694-a594-11e2-93f5-97831e3d1a96.png)

**Comment by evansims** [comment]
I'll get these embed sizing issues knocked out today.

**Comment by evansims** [comment]
I've fixed this issue.
