### ISSUE TITLE
Layout issues with close X in corner of modal

### ISSUE THREAD

**Issue by sethburtonhall** [ushahidi/crowdmap-issues#310]
http://cl.ly/QfJ6

![screen shot 2013-08-06 at 10 41 19 am](https://f.cloud.github.com/assets/1033332/917577/02eae818-fea7-11e2-944b-c053cc5d4f9a.png)

Layout adjustment needed to the closing X. Make smaller and centered.

Also, upload image is overlapping media upload icons.

**Comment by brianherbert** [comment]
Closing X issue is valid.

Image overlap is a duplicate of #308

**Comment by evansims** [comment]
This flow has been entirely reworked with the forthcoming UI update. Marking obsolete.
