### ISSUE TITLE
Clicking "new map" leads to nowhere

### ISSUE THREAD

**Issue by danielmichaelwolf** [ushahidi/crowdmap-issues#311]
I tried creating a new map on safari and safari mobile, as well as chrome and Firefox, but the screen just darkened a bit and nothing happened. This seems like a pretty big issue!

Thanks,
Daniel

**Comment by evansims** [comment]
Hi Daniel, that would indeed be a pretty big issue. :wink: I'm checking into it now, thanks.

**Comment by danielmichaelwolf** [comment]
Thanks!

**Comment by danielmichaelwolf** [comment]
I'm trying to develop a tool to collect input on where new bike parking is needed from a community, and Crowdmap seems like the perfect tool, but it's been giving me various bugs, suggesting it might be a little while before it's ready for prime time. Do you have a sense of when it will reach that polished stage?

Thanks,
Daniel Wolf

**Comment by evansims** [comment]
Sounds like a great idea! There really aren't any show stopping bugs that I'm aware of, aside from this (which appears to have popped up either today or yesterday; still tracking down the cause.), but we're finishing up a major UI revision that will go live this week that will greatly improve the mobile experience and fix some inconsistencies.

**Comment by danielmichaelwolf** [comment]
Awesome! If you could let me know when that happens, I'd really appreciate it.

**Comment by evansims** [comment]
Sure Daniel; ping me at evan@ushahidi.com so I have your email address and I'll give you a heads up when it's live.

Just pushed a hotfix to resolve this bug. Thanks again for the heads up.
