### ISSUE TITLE
Location address search not working

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#312]
It doesn't appear to do anything at all.

**Comment by brianherbert** [comment]
Locating position appears to get stuck after accepting to share location. This should also be auto selected after being found.

![screen shot 2013-08-08 at 10 09 52 am](https://f.cloud.github.com/assets/106068/928930/50318d2c-ffc7-11e2-8618-8246b1a12538.png)

**Comment by evansims** [comment]
I'm not seeing that issue on my end

**Comment by brianherbert** [comment]
Curious... is it possible to embed a youtube video in github issues... (it's apparently not).

http://www.youtube.com/watch?v=LPoLFArW-hg

The video quality here is pretty crap but you can see nothing happens.

**Comment by brianherbert** [comment]
Looks like it's working flawlessly in Chrome now, just not Firefox.

**Comment by evansims** [comment]
Confirmed fixed (as far as I can tell) in forthcoming UI update.
