### ISSUE TITLE
Search returns everything

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#314]
Searching for the #cmupdates hashtag in search returns all posts (Even in Chrome!).

https://crowdmap.com/search/?q=%23cmupdates

![screen shot 2013-08-09 at 3 03 25 pm](https://f.cloud.github.com/assets/106068/936562/6f831914-00b9-11e3-8c16-8114d65f68e7.png)

**Comment by evansims** [comment]
Confirmed fixed in forthcoming UI update.
