### ISSUE TITLE
Posts that start with a hashtag are interpreted as an h1 in markdown

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#32]
This one is tricky. How do we reconcile this? cc @evansims 

![Screen Shot 2013-04-15 at 9 07 40 PM](https://f.cloud.github.com/assets/106068/380486/392e10fc-a5c5-11e2-8b0a-cbd6fd7837d1.png)

**Comment by evansims** [comment]
Fixed
