### ISSUE TITLE
Map View 

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#320]
Would it be possible to show more in the Map view /Search to highlight why I would want to engage with the content?  I want to know why I should open one map vs. another. 

http://dl.dropbox.com/u/34693557/Screenshots/g~.png
![g](https://f.cloud.github.com/assets/1216707/1012706/223c2a1c-0b75-11e3-95ce-b4a7b903677d.png)

**Comment by brianherbert** [comment]
I think reading the map descriptions should help there. Other than that, with the location and keyword filters, I'm not sure what else we know about the map to show.

Issue #321 might help surface more interesting maps by default if we can figure out a way to indicate trends.

This is very closely related to #321 so closing this ticket.
