### ISSUE TITLE
Map Features - Search + Highlights

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/crowdmap-issues#321]
When I come to this page, I would like to see the following:
what are the top maps of the day by hits and content
what are some curated maps of good work or featured use cases

https://crowdmap.com/maps/

![g](https://f.cloud.github.com/assets/1216707/1012718/5e182b6c-0b75-11e3-8d06-de5fed45c2e0.png)

**Comment by evansims** [comment]
We're introducing a curated "editor's picks" section as a first step towards this. I'd also like to see a proper trending maps/posts part to this down the road, but that will have to come later.
