### ISSUE TITLE
Can't enable  auto-posting from instagram or twitter

### ISSUE THREAD

**Issue by DBaranskiW** [ushahidi/crowdmap-issues#332]
I've followed the instructions but when I change my settings to enable auto-posting from Instagram, it takes me to Instagram, it says 
"Hi dbaranskiw, Crowdmap is requesting to do the following:

Access your basic information"

But when I click authorize it redirects me back to the Crowdmap settings page, no change and not authorized.  Try again, same thing.

Also this same thing happens when I try to authorize "Import my Twitter posts".

My friend Marj is running into the same problem.  I've tried this from Firefox, I've tried it from Safari --- neither works.  help.

**Comment by brianherbert** [comment]
I'm confirming this.

Working on a fix.

**Comment by brianherbert** [comment]
Alright, this should be working now.

@DBaranskiW If you connect your account and you notice there isn't a yellow check mark indicating that you have made the connection, refresh the page and it should come up. That lag time is related to another issue.

Thanks!!

**Comment by DBaranskiW** [comment]
Thanks Brian, it is indeed working now!   Great.

**Comment by brianherbert** [comment]
Excellent. Thanks for confirming! Please continue reporting any other issues you see, or make featured requests here on github in the future!

**Comment by DBaranskiW** [comment]
Thanks, I'm posting my next one now.
