### ISSUE TITLE
Now that Instagram is connected, how do I post?

### ISSUE THREAD

**Issue by DBaranskiW** [ushahidi/crowdmap-issues#334]
Ok, I'm in Istagram with hash tags operational -- but I'm not seeing an obvious way to post to Crowdmap.  Please walk me through, step by step, how to post from my phone using Instagram.

Thank you

**Comment by brianherbert** [comment]
Would you like to post to your map using hashtags or auto post your own personal "instagrams" to your personal feed?

**Comment by DBaranskiW** [comment]
Hashtags please

#candle4syria

**Comment by DBaranskiW** [comment]
Ok, we can see how to post to various social media but Crowdmap is not included.

When I try posting with the #candle4syria as hashtag, it posts to Instagram but not to our Crowdmap.

**Comment by brianherbert** [comment]
If you go to you map settings (as the map owner) and scroll down, there is a section where you can add the hashtag. When someone posts to Instagram with that hashtag, it will show up within a few minutes on your map.

**Comment by DBaranskiW** [comment]
Oh, I see it now.  There is a new section (enabled when I enabled Instagram), below the Collaborator section which specifically allows me to add Instagram hashtags.

I've had regular hashtags in my map all along - but that's not enough.  This needs Instagram hashtags.  I'll try it now.

**Comment by DBaranskiW** [comment]
It didn't work.   I confirmed that I saved #candle4syria in the Add Instagram Tags section of my map.  I included #candle4syria in the caption area of  instagram post and successfully posted.  It did not come through on my map.

Could you try it?

**Comment by brianherbert** [comment]
Sorry it took me a day to respond, I've been traveling. I just took a look and it seems the problem is there's the actual hash (#) in the tag. We don't have any indication that you shouldn't add that so it's not your fault. We'll make that process easier (auto strip the hashtag, etc). I went ahead and removed the hashes for you so it should start pulling within a few minutes.

**Comment by DBaranskiW** [comment]
Wow, the Instagram is working!   Thank you for getting back to me.   Now it becomes useful, interesting.  We're too late to meet our original goals today but are sure learning a lot from the implementation.

I'll post more questions now.

**Comment by DBaranskiW** [comment]
The photo came through from Istagram but not location - not for mine, nor for any others posting.   What needs to happen on the Instagram side or on the Crowdmap side to get location transferred?

**Comment by brianherbert** [comment]
When you are posting on Instagram, are you adding a location? Can you give me an example post that came from Instagram that should have a location so I can look into it?

**Comment by DBaranskiW** [comment]
I did not mean to close this issue -- can you re-open it?

Please take a look at the post from Rudy on #Candle4Syria.     I was with him when he took the photo, added the hashtag, and then he added place name Menlo Park CA.   Instagram successfully showed that on the Instagram map -- but it did not come through on Crowdmap.com

**Comment by brianherbert** [comment]
Okay, I see what's going on. The location is being saved but we aren't saving a name along with it. I'll see what we can do about that.

If you visit the post directly, you can see that it is mapped https://crowdmap.com/post/29584

**Comment by brianherbert** [comment]
Give it a shot now. I just pushed a fix.

**Comment by DBaranskiW** [comment]
Looks good!  I think we've got it!  Thanks for your help with this.
