### ISSUE TITLE
Require Approval:  how is this supposed to work?

### ISSUE THREAD

**Issue by DBaranskiW** [ushahidi/crowdmap-issues#335]
Right now, http://Candle4Syria.crowdmap.com  is set to automatic approval but if things pick up, we'll want to require approval.  

How do we do this?   We added a collaborator but there may be a bug.    Our collaborator has no access to the internal Settings tab.

Sincerely,
Donna

**Comment by brianherbert** [comment]
There is a setting in the map settings to set the approval method (auto or moderated).

The collaborators have access to the moderation functionality directly on the feed of posts. This bar looks like this:

<img src="http://f.cl.ly/items/0d402p2n1S3u073F383L/Screen%20Shot%202013-09-19%20at%206.06.20%20PM.png">

Clicking on "Moderate posts" will all you to select and approve posts. The bar will flip over to reveal the following options:

<img src="http://cl.ly/image/343k0Z0C2N1n/Screen%20Shot%202013-09-19%20at%206.07.07%20PM.png">

**Comment by DBaranskiW** [comment]
Thank you for this detailed explanation.  I'm waiting to hear from the others on my team to confirm it is working well.

Suggestion:  change the word Collaborator to Moderator. 
Posting Review Team or  Approval Team or Moderating Team would also work.

**Comment by brianherbert** [comment]
Thanks for the feedback. I'm going to close this issue in the meantime.
