### ISSUE TITLE
How to request an entirely new map tile

### ISSUE THREAD

**Issue by DBaranskiW** [ushahidi/crowdmap-issues#336]
We would like a map tile that shows congressional districts in addition to state boundaries.  We have the data -- who can we contact in the map-provider community to request this new base map tile?

**Comment by brianherbert** [comment]
We don't currently allow custom map tiles. However, I've been wanting to allow people to hook up to a mapbox account (http://mapbox.com) and use custom tilesets from there. Would you be interested in playing around with that if we build out the feature?

**Comment by DBaranskiW** [comment]
Yes!   I wrote back as soon as I saw your message but somehow my comment was not posted.  We're definately interested in exploring this with you.    Please tell me what to do to get started.   If email or phone would be helpful for further discussion, let me know.

**Comment by brianherbert** [comment]
Great! I actually pushed up a first version of this feature a few days ago. If you go to your map settings, you can enter your Mapbox username and then select any public map from the list that pops up (It takes a second).
