### ISSUE TITLE
Some embeds don't have data but we still save them

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#34]
We should display the warning that there is no embed for a link on the create dialogue when there's no content to display for a given embed rather than just show the link, since the link is already in the message body.

![Screen Shot 2013-04-18 at 10 08 22 AM](https://f.cloud.github.com/assets/106068/394536/898488aa-a7c4-11e2-85db-d931dd731bc1.png)

**Comment by evansims** [comment]
I've made some alterations to the externals handling that should fix this. Feel free to reopen or make adjustments if you notice any cases that this misses.
