### ISSUE TITLE
On a new account 'My Maps' page - loading issue

### ISSUE THREAD

**Issue by dkobia** [ushahidi/crowdmap-issues#340]
- Created a new crowdmap account
- Went to 'Your Maps' page -- also should this be labeled _'My Maps'_ ... confusing
- The three sections display 'Loading your maps, one moment please...' (below) -- also should this be labeled _'Loading my maps..'_ ?
- And I don't have any maps yet... should just be blank

![screenshot 2013-11-26 07 04 18](https://f.cloud.github.com/assets/184092/1621670/65bee36a-5693-11e3-849e-5ba4969f8e6c.png)

**Comment by brianherbert** [comment]
@evansims Is the behavior on this page different in the new design?

**Comment by evansims** [comment]
Good catch. This is indeed wired up totally differently with the redesign. I'll leave this open in the meantime.

**Comment by evansims** [comment]
Confirmed fixed in forthcoming UI update.
