### ISSUE TITLE
Navigation error

### ISSUE THREAD

**Issue by maparebel** [ushahidi/crowdmap-issues#344]
When I click in a geopoint I get a popup windows. 
If i close the windows by clicking the "close button" (see attached image, mark 1) then I can still navigate the map and open different geopoints.

But if I click on the map instead of closing the windows  (see attached image, mark 2), then I can navigate the map but I can't open any other geopoint.

![issue6](https://f.cloud.github.com/assets/6531917/2027130/0e60c9c8-88aa-11e3-9be0-61a26b305bb6.jpg)

**Comment by evansims** [comment]
We're replacing how this function operates in an upcoming update, so I'm going to close this one now. Thanks for your report.
