### ISSUE TITLE
Navigate through different maps

### ISSUE THREAD

**Issue by maparebel** [ushahidi/crowdmap-issues#345]
I have published a post in different maps.
When I open this post and I try to see it in a different map by clicking into the title of a different map, everything fails. I can't see the different map, and neither can open any other geopoint of the current map.
![issue7](https://f.cloud.github.com/assets/6531917/2027164/1e4f73ba-88ab-11e3-813e-093f5675cc60.jpg)

**Comment by evansims** [comment]
We're replacing how this function operates in an upcoming update, so I'm going to close this one now. Thanks for your report.
