### ISSUE TITLE
Links doesn't works

### ISSUE THREAD

**Issue by maparebel** [ushahidi/crowdmap-issues#346]
In the wall links to different websites works, but in the popup windows of the geopoints doesn't works 
![issue8](https://f.cloud.github.com/assets/6531917/2027180/7bde7666-88ab-11e3-976c-0021181e35d1.jpg)
Big problem it is that after clicking a link in a geopoint you can not open any other geopoint.
Same behavior happens with #hashtags

**Comment by evansims** [comment]
We're replacing how this function operates in an upcoming update, so I'm going to close this one now. Thanks for your report though.
