### ISSUE TITLE
Edit button it's missing in the wall

### ISSUE THREAD

**Issue by maparebel** [ushahidi/crowdmap-issues#348]
"Edit button" it is not available in the wall. 
![issue9](https://f.cloud.github.com/assets/6531917/2027238/bbcf64aa-88ac-11e3-971a-d1a4554efb4b.jpg)

I have to make 2 steps to reach it

First click on the date of the post
![issue11](https://f.cloud.github.com/assets/6531917/2027247/0d52a38c-88ad-11e3-8df1-f0b418cf5de5.jpg)

And only then I can see the Edit button

![issue12](https://f.cloud.github.com/assets/6531917/2027255/3c35cd28-88ad-11e3-91d8-015b755646e2.jpg)

**Comment by evansims** [comment]
Confirmed fixed in forthcoming UI update.

**Comment by maparebel** [comment]
Great!
Do you know more or less when will be this update?
Regards
