### ISSUE TITLE
Locate by address doesn't works

### ISSUE THREAD

**Issue by maparebel** [ushahidi/crowdmap-issues#349]
If I try to locate a post searching by an address I don't get any result. (Using chrome, I don't know with firefox)
![issue13](https://f.cloud.github.com/assets/6531917/2027280/568fe07c-88ae-11e3-9eaf-898ef1dabae0.jpg)

**Comment by evansims** [comment]
We've rewritten how this functionality works in an forthcoming update, but I'll leave this open to ensure we test it thoroughly.

**Comment by maparebel** [comment]
Ok. When you click "add new place" same issue happens. 
![issue15](https://f.cloud.github.com/assets/6531917/2039423/4716ffba-89a1-11e3-96a5-ac7901730a42.jpg)

**Comment by evansims** [comment]
Confirmed fixed in forthcoming UI update.
