### ISSUE TITLE
Highlight Expand map button

### ISSUE THREAD

**Issue by maparebel** [ushahidi/crowdmap-issues#350]
The "Expand map" button it is very small and it is not easy to see it. A lot of users, new users of crowdmap, don't click it.

![issue14](https://f.cloud.github.com/assets/6531917/2027321/44ebfdfa-88af-11e3-83c6-d28804cc1c9e.jpg)

I suggest:

Make it bigger
Make it green color
Use "Open map" instead of "Expand map" (people that don't speak english know this word)

**Comment by evansims** [comment]
We're replacing how this function operates in an upcoming update, so I'm going to close this one now. Thanks for your report though.
