### ISSUE TITLE
Twitter link

### ISSUE THREAD

**Issue by maparebel** [ushahidi/crowdmap-issues#353]
I don't know if it is possible: 

When you post a crowdmap link in twitter, the post shows the picture of the profile of the map that you link. It is ok, problem it is that when users click the picture they get a popup windows with the full-size picture. I think it would be better to open a new browser tab with the map. 

![issue20](https://f.cloud.github.com/assets/6531917/2039668/8af7dfba-89a6-11e3-87ee-82f1937ad5e4.jpg)

**Comment by evansims** [comment]
Hmm it sounds like we might need to review our OpenGraph tags. I'll look into this, thanks!

**Comment by evansims** [comment]
Confirmed fixed in forthcoming UI update.
