### ISSUE TITLE
Not possible to download images

### ISSUE THREAD

**Issue by maparebel** [ushahidi/crowdmap-issues#354]
It's not possible to download an image. 
I right click on my mouse, click "save as" option, but it is not possible to download images in GIF or JPEG format.
![issue20](https://f.cloud.github.com/assets/6531917/2042851/b005ddd6-89d6-11e3-9b24-a9edadc74df7.jpg)

**Comment by evansims** [comment]
Thanks for your report; this is actually intended by design.
