### ISSUE TITLE
Password set/recovery once-over

### ISSUE THREAD

**Issue by evansims** [ushahidi/crowdmap-issues#357]
Got a report of complex passwords having recovery/setup issues. Do a once-over on these to ensure things are working as expected.

It also appears CrowdmapID emails are no longer being sent out via Sendgrid as they should be. This in particular needs resolved immediately to avoid spambox blackholes.

**Comment by evansims** [comment]
Tagging @shadowhand to keep him apprised of updates

**Comment by evansims** [comment]
It appears `<` and `>` tags are being sanitized by our input processor, resulting in complex passwords using those characters being malformed.

Examples:
- Passing `password<test`results in the hash of `password` being stored.
- Passing `password<test>password` results in the hash of `passwordpassword` being stored.

Patch is being tested now.

**Comment by evansims** [comment]
A patch has been pushed and is propagating to datacenters. @shadowhand would you mind seeing if this fixed it for you? I will need to review our other products' implementations to ensure they aren't bugged either.

**Comment by shadowhand** [comment]
No change, using a password with special characters is still broken.

**Comment by evansims** [comment]
Herp derp, forgot a step in that last commit. Give it another try.

**Comment by shadowhand** [comment]
Was able to change my password and login successfully. Thanks!
