### ISSUE TITLE
Mobile menu is unusable because of background color/image

### ISSUE THREAD

**Issue by shadowhand** [ushahidi/crowdmap-issues#360]
Clicking on the mobile menu is nearly worthless because the menu flyout doesn't have a background color, letting the site background (black with white dots) bleed through. See screenshot:

![Chrome on Android 4.4](https://f.cloud.github.com/assets/38203/2140201/fd6d2450-9348-11e3-898a-7ad0bddefa8f.png)

**Comment by evansims** [comment]
This is resolved with the pending design update. The slide out menu has been rewritten, as this implementing was kind of janky. :+1:
