### ISSUE TITLE
Failed crowdmap login repopulates password field

### ISSUE THREAD

**Issue by shadowhand** [ushahidi/crowdmap-issues#361]
A failed login attempt should never repopulate a password input, as it can be combined with an XSS vector to scrape user passwords. When login returns with failure, the password input should be immediately cleared.

**Comment by evansims** [comment]
We never repopulate password fields, actually; the login process is done via a background ajax request so the page never reloads. You're right though we should be clearing that field after failed attempts. I'll ensure this gets in with the design update.

**Comment by evansims** [comment]
Confirmed fixed in forthcoming UI update.
