### ISSUE TITLE
Removing Collaborators Doesn't Work

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#367]
From @zhibek

When passing a DELETE on a collaborator, an error of "Passed user is already collaborating on this map" is returned, but this error seems to relate to the POST to this resource rather than the DELETE.

**Comment by zhibek** [comment]
![screenshot from 2014-03-03 14 3a43 3a13](https://f.cloud.github.com/assets/1309381/2319426/d782632e-a37c-11e3-9188-0832bbf80104.png)

Here's a screenshot of the problem using crowdmap.com - the Net panel shows the error coming from the Crowdmap API.

**Comment by zhibek** [comment]
Mentioning @yakobadaba who originally reported the issue, so he can track this.

**Comment by brianherbert** [comment]
This should be fixed now. @zhibek and/or @yakobabada, can you confirm?
