### ISSUE TITLE
API: Saving an edited post fails if map_id isn't passed

### ISSUE THREAD

**Issue by zhibek** [ushahidi/crowdmap-issues#368]
When using the API, if sending a PUT request to edit a POST, a generic error is returned (although the actual save succeeds) if a map_id property isn't passed in the data of the call.

![screenshot from 2014-03-04 19_32_16](https://f.cloud.github.com/assets/1309381/2323976/5af794b8-a3c3-11e3-808b-5288c46976b6.png)

**Comment by evansims** [comment]
Fixed this awhile ago but forgot to close. Many thanks for the report.
