### ISSUE TITLE
Safari Crashs when selecting Password Field at Login

### ISSUE THREAD

**Issue by jonshuler** [ushahidi/crowdmap-issues#370]
When you're at the homepage and you go to log in, clicking or tabbing into the Password field causes the page to crash and be reloaded.  This ONLY happens for me in Safari (Version 7.0.2 (9537.74.9)).  My suspicion is that it has to do with some sort of password auto fill extension or Mac's own password keychain, but I'm not totally sure.

**Comment by evansims** [comment]
I am able to reproduce this, but I'm at a loss as to why it would be occurring. Disabling the 1Password extension seemed to fix the crash for me, though, so I'm guessing it's a bug relating to their extension (though I haven't seen it happen anywhere else.)

I can confirm this is not happening with the forthcoming UI update though, so I'll go ahead and close this for the moment. Thanks for the report!

**Comment by jonshuler** [comment]
Cool!
