### ISSUE TITLE
Crowdmap April 2014 UX Update

### ISSUE THREAD

**Issue by evansims** [ushahidi/crowdmap-issues#371]
**This thread is for discussing issues with the forthcoming April UI Update, currently on staging for testing.** This update will be getting pushed to production in the next week or so — or, more realistically, whenever the we feel it's ready for prime time.

Known issues:
- Welcome page is ugly and busted. Needs updated. I has plans for this.
- ~~Registration UI may be broken.~~ Fixed.
- ~~User settings page and related pages (like SMS setup) need wired back up.~~ https://github.com/ushahidi/crowdmap-issues/issues/382
- Map settings page needs updated to new style.
- Map interactivity is currently read-only. Need to wire various functions back up.
- You can't currently set a map marker for posts. Need to wire up a UI widget for this still.
- ~~Externals on create post flow haven't been wired back up yet.~~ Fixed.
- The "Trending Topics" page is going to look like it doesn't work, but this is only because staging doesn't really have any content on it to speak of.
- ~~Need to finalize embedded/iframe view stuff.~~ Done.

**Comment by evansims** [comment]
~~Photo uploads are currently failing on staging. Trying to determine why.~~ Fixed

**Comment by brianherbert** [comment]
~~Pinning a location to a new post defaults to Illinois when I'm in South Korea.~~ Should be fixed now,

**Comment by brianherbert** [comment]
~~Auto-embeds on posts needs to be working (already mentioned in chat with @evansims)~~ Done

**Comment by evansims** [comment]
~~Freshly created maps aren't showing yourself as a curator, just a follower.~~ Fixed.

**Comment by evansims** [comment]
~~Map listings template is failing to load for some reason, making it difficult to add a post to a map. Probably a merge issue. Looking into it.~~ Fixed.

**Comment by evansims** [comment]
Maps, user profiles and location portals have a flash of unstyled content when loading; specifically, you'll see the mobile and desktop headers briefly before the appropriate one is disabled.

**Comment by evansims** [comment]
~~Need to wire back up "delete post" option for post authors.~~ Fixed.

**Comment by evansims** [comment]
~~Discovery page is throwing an error at the moment. Will fix shortly.~~ Fixed (though the page will appear empty because nothing connected to staging has been featured.)

**Comment by maparebel** [comment]
If you need help for testing tell me.

**Comment by evansims** [comment]
@maparebel That'd be great, any help is appreciated. Our staging server is at http://crdmp3.com/global/ if you want to hit things there and see what you can break. You'll need to [register for a new account](http://crdmp3.com/register) as staging is on a different authentication server from live/production.

If you just want to reply to this issue with any bugs you find that would probably be easiest.

**Comment by evansims** [comment]
- Posting a comment seems only work the first time and then requires a page load; subsequent comments don't get pushed through correctly.
- Place search in the Create Post UI is throwing a Leaflet-related JS error, and is therefor not working.

**Comment by evansims** [comment]
Things appear to be working well on IE 10+. I don't have access to lesser versions of IE at the moment to test there, but I wouldn't hold my breath.

**Comment by maparebel** [comment]
register is not possible with Chrome. After fill in the form I get this error message 
![image](https://cloud.githubusercontent.com/assets/6531917/2594243/6741c9da-ba8b-11e3-8f36-2b665469843a.png)

**Comment by evansims** [comment]
@maparebel Whoops, sorry about that. I think I see the problem. Give me a bit to push a fix.

**Comment by evansims** [comment]
@maparebel Give this another try when you have a minute. Thanks.

**Comment by maparebel** [comment]
Thanks now I can log in. I like the new version!

**Comment by evansims** [comment]
@maparebel Thanks, very glad to hear you like it!
