### ISSUE TITLE
Updating profile summary does nothing

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#382]
Attempting to write a profile summary or change the user's full name and hitting "Update Profile" does nothing.

**Comment by brianherbert** [comment]
Github lies. I edited @evansims post and it says @evansims did it. Bad GitHub, bad!

**Comment by evansims** [comment]
![](https://dl.dropboxusercontent.com/u/23890/tumblr_inline_mmcompbbvP1qz4rgp.gif)
