### ISSUE TITLE
Password Reset Email URL Incorrect

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#405]
To reproduce, send yourself a password reset for your account, click the link in the email. That link takes you back to the form to submit a password reset request instead of the form to create a new password. The URL in the password reset email hasn't changed in as long as I can remember.

**Comment by zhalloran** [comment]
I can't reproduce this. I've reset my password many times without encountering this behavior. Were you logged in at the time?

**Comment by brianherbert** [comment]
I went back and tried again and it worked. I'm honestly not sure what could have caused this, other than some leftover cookies, but I'm positive I cleared them. If I see this crop up again, I'll reopen this or open another issue.
