### ISSUE TITLE
Accidentally deleted "user" (trying to change email) now cannot manage incoming reports! What can I do?

### ISSUE THREAD

**Issue by Burundik** [ushahidi/crowdmap-issues#409]
I created my account a year ago on Crowdmap for a mapping course, but hadn't used it until recently. I was trying to manage the users in the account so that I could change my email. I deleted the first one (after adding a new user with the email I wanted - it wasn't working to change the email). Now when I login, I can see the map, my dashboard, etc. but cannot see new reports, accept them, etc. How can I restore this? I'm basically locked out from administration of my account. Please help!

It's quite urgent because the protests in Bujumbura are ongoing and I'm the only one mapping (that I know of)

Here's the map: https://2015burundi.crowdmap.com/

**Comment by brianherbert** [comment]
Following up on this via email. Closing.
