### ISSUE TITLE
Include big button on homepage to switch back to classic

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#43]
Some people may be confused when we do the switchover, we need to make it really clear how to get to the classic version.

**Comment by brianherbert** [comment]
Maybe we can just stick a logo above the link that we have now.

**Comment by heatherleson** [comment]
When I click on "Go back to Crowdmap classic" it does not take me there. http://dl.dropbox.com/u/34693557/Screenshots/9r.png

Should this be a separate bug?

**Comment by heatherleson** [comment]
typing : Crowdmap.com/switch/classic does not reroute me, so I faked it and go here to go back - https://crowdmap.com/explore/mhi_extras/switch/classic  or https://crowdmap.com/mhi

Wiki page for instructions until we have a work around - https://wiki.ushahidi.com/display/WIKI/Switching+between+Crowdmap+and+Crowdmap+Classic

**Comment by heatherleson** [comment]
The Switch to Crowdmap classic in the User menu also loops back to new crowdmap - http://dl.dropbox.com/u/34693557/Screenshots/ag.png

**Comment by evansims** [comment]
The link works but your browser is caching /. You need to refresh after following the link. It's a caching but were aware of.

**Comment by heatherleson** [comment]
That is going to be a pain point

**Comment by brianherbert** [comment]
Just to make sure this ticket stays on topic moving forward, this is about adding UI for switching, not about the mechanism for switching.

**Comment by evansims** [comment]
![](https://dl.dropboxusercontent.com/u/23890/runaway.gif)
Runaway ticket, RUNAWAY TICKET

**Comment by heatherleson** [comment]
Opening separate ticket for mechanics of switching

**Comment by brianherbert** [comment]
I've added a very difficult to miss logo to switch back to classic on the homepage.
