### ISSUE TITLE
Clicking some links in the the top right dropdown menu do nothing

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#44]
I'm trying to click links in the grey area (Classic, About, Bugs, etc) which all don't work. Anything that is a regular link doesn't do anything. I think these are being caught by a click event handler somewhere. @evansims I remember you were looking into this exact issue a while back? I can't seem to find an open ticket for that anywhere unless it was fixed and then reintroduced down the line.

![Screen Shot 2013-04-18 at 8 03 00 PM](https://f.cloud.github.com/assets/106068/396099/9fc2c930-a817-11e2-90a8-46c43fdf4b3f.png)

**Comment by evansims** [comment]
Fixed, thanks

**Comment by heatherleson** [comment]
Bug is back.

Click on http://dl.dropbox.com/u/34693557/Screenshots/9u.png. 
No dropdown. Unable to login 

Workaround - https://crowdmap.com/login/ to get into tool

**Comment by evansims** [comment]
This is a different bug, but possibly related. Opened a new ticket at #103 to track this. Thanks!
