### ISSUE TITLE
New Crowdmap branding needs revisited. #design

### ISSUE THREAD

**Issue by evansims** [ushahidi/crowdmap-issues#45]
Recreating this issue from the [UI repo](https://github.com/ushahidi/Crowdmap-New-UI/issues/16) and Basecamp chats so we can track this easier.

I agree with Heather that we need clearer branding. By removing the border and definition around the globe in New we are making it so abstract that it becomes completely unclear as to what it's supposed to be.

As a test I showed the New logo to my parents and a couple friends. One of my friends guessed what it was. Everyone else had to be told.

I'm not saying we should reuse our Classic globe; New's branding should be different and symbolic of our new direction and focus. We need recognizable and distinctive branding for New that is on par with Classic.

/cc @heatherleson @brianherbert @Jepchumba @ehersman @aoduor

**Comment by brianherbert** [comment]
Hey guys, Caleb put together comps for a couple different variations on the Crowdmap logo back before we launched. I just checked and you all should now have access to the Crowdmap_Internal folder. It has badges, logos, etc in there. http://cl.ly/3g1v102z4346 is a file with some color variations.

I wouldn't mind rounding out the logo, but I think we should keep it compatible with the soft yellow background. I'm to suggestions though.

**Comment by brianherbert** [comment]
Since it's been a while, I'm going to close this. If anyone wants to keep this open and has something to contribute, go for it.

**Comment by heatherleson** [comment]
I'm a touch confused. The change is not completed, so it is an open item. I looked at Caleb's work. The last logo file is favourable, but it is Crowdmap Classic.

**Comment by brianherbert** [comment]
I assumed there was no more interest since it sat dormant for almost a month. If you would like to reopen this, that's fine. We probably won't have any design resources to put on this to come up with new mockup a though.

**Comment by evansims** [comment]
Reopening per our emails. This really needs to be addressed, even if it isn't right this moment due to our design-side constraints, but there a few things more important than product branding - and I think ours is really lacking right now.

**Comment by brianherbert** [comment]
Moving to Basecamp.
