### ISSUE TITLE
Some names are longer than their boxes in photos view

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#48]
Reusing this screenshot from other issue.

![Screen Shot 2013-04-19 at 2 53 07 PM](https://f.cloud.github.com/assets/106068/400641/a578910e-a8b5-11e2-92b9-5cc5c1a918c9.png)

**Comment by evansims** [comment]
Fixed. I also made these avatars smaller and, dare I say it, sexier.
