### ISSUE TITLE
Skinny embeds seem to float right

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#53]
Is this the desired behavior? 

![Screen Shot 2013-04-22 at 2 10 48 PM](https://f.cloud.github.com/assets/106068/407674/127c2020-ab0b-11e2-81c9-f2ce5cc70400.png)

**Comment by evansims** [comment]
That's intentional and unique for Kickstarter embeds. It was the only way I could style those without them looking really weird.

**Comment by brianherbert** [comment]
Sounds good to me.
