### ISSUE TITLE
Get Instagram auto-posting working again

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#57]
This has been broken for a while on production.

**Comment by evansims** [comment]
It's still working on staging, so I'm thinking we must have a pingback or something somewhere blocked, possibly by Gatekeeper. If you can pop me an email as to how this works I can check our rules and conditions. Trying to figure it out by looking at the code but a bit lost. <3

**Comment by brianherbert** [comment]
So all the action happens on the API (subscription setup details are in the API repos README file). Does the Gatekeeper assign routing cookies for api.crowdmap.com? If not, then the Gatekeeper may not be the issue.

Instagram should be pushing to us at the http://api.crowdmap.com/v1/thirdparty/instagram/realtime/ URL so perhaps we can try and log any requests that hit that URL.

instagram_add_realtime_photo() is fired when they push to us letting us know about the new photos in case you aren't sure where to look. We're saving the details of the push in the cron table, which is later checked by the cron job.

**Comment by evansims** [comment]
Hm, not Gatekeeper then. The LB bypasses that for the API. Will do some digging.

**Comment by brianherbert** [comment]
This is working again thanks to routing changes and monkeying with Instagram subscriptions.

Closing.
