### ISSUE TITLE
Image swapped on resize

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#58]
Looks like @aoduor posted a photo that was resized as a different image.

https://crowdmap.com/post/272/reasons-why-a-trampoline-will-be-a-functional-requirement-when-i-get-my-own-place 

I checked all of the resized images and they are all correct except the large size, which is filename_l in the db.

**Comment by evansims** [comment]
What a weird bug. I'll see if I can figure out anything with this today.

**Comment by brianherbert** [comment]
Sorry, I didn't get to this today. Only thing I can think of without digging into it is there's some kind of naming collision so we may need to do something with unique filenames on rackspace (not 100% sure about that though).

**Comment by evansims** [comment]
I've added an additional check for CDN upload filenames and swapped out our unique filename generator to use [uniq_id](http://php.net/manual/en/function.uniqid.php). Between this and the reworking to our media resampling last week, I'm sure we've squashed the culprit of this bug. If we encounter it again we can reopen.
