### ISSUE TITLE
Lightbox view is completely busted. #all

### ISSUE THREAD

**Issue by evansims** [ushahidi/crowdmap-issues#6]
![Screenshot_4_13_13_3_27_PM-2](https://f.cloud.github.com/assets/3093/377084/9f645762-a478-11e2-9738-3e54ab0823c9.png)

How do we think we should we be approaching the lightbox view? Should it just display the image, or the full post?

In my opinion it should be a lightweight full view of the post photo and nothing else. It's too cumbersome to try and rangle all the functionality of the post detail view into a lightbox, IMHO.

**Comment by brianherbert** [comment]
Agreed. I think we should just show the image. It also reduces complexity that way.

**Comment by evansims** [comment]
Cool, I'll assign myself to tackle this one. Thanks.

**Comment by evansims** [comment]
I've disabled lightbox view until I can get it working in a more acceptable manner. Clicking post photos will just redirect to the post detail page in the meantime.
