### ISSUE TITLE
Using location picker twice without a page refresh inbetween doesn't work

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#66]
Nothing happens when you make one post with a location and then try to create a second one.

![Screen Shot 2013-04-23 at 10 41 35 AM](https://f.cloud.github.com/assets/106068/412464/ff37e45c-abb6-11e2-90b5-922a9089e25c.png)

**Comment by evansims** [comment]
Fixed, will push to production shortly.
