### ISSUE TITLE
Add who liked a post

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#70]
I want to know who the three people are who liked this

![Screen Shot 2013-04-24 at 10 28 02 AM](https://f.cloud.github.com/assets/106068/417860/53f5de14-ac7e-11e2-82fc-a099e85d181e.png)

**Comment by evansims** [comment]
Post details now display up to 5 avatars of users who liked a post. We'll want to iterate upon this but it's a start.

![screen shot 2013-06-08 at 9 42 51 pm](https://f.cloud.github.com/assets/3093/628410/4f7ca300-d0ae-11e2-89ff-7997105c8787.png)

**Comment by brianherbert** [comment]
Sir, way to carry the ball this week. You're awesome ;)

**Comment by evansims** [comment]
Confirmed fixed in forthcoming UI update.
