### ISSUE TITLE
Externals not added if the url is the last thing typed without hitting space or enter

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#74]
I'll consider this a bug, people who paste the URL at the end of their post probably expect the URL to become an attachment.

Currently, when you type a URL and hit space or enter, the post parser will convert it into an attachment. If you type your message, then paste your URL without hitting any other keys and hit post, it will not be an attachment.

But perhaps it should be, then if the user really didn't want that, they could go back and edit it.

**Comment by evansims** [comment]
I'm open to the idea, but it will be tricky from a UX perspective to do this without annoying folks with a prompt every time they go to make a post. I don't think making users go back and edit their post to remove it after the fact is a solution, either, if we don't give them an option not to add it in the first place.

For reference, Facebook handles it identically to how we are now, requiring a space or enter event before parsing (but they are automatically added for comments.)

**Comment by brianherbert** [comment]
I think rather than a prompt, we would just add it. The only reason I bring this up is almost everyone on our team who has tested Crowdmap and attempted to embed something (Erik, Angie, Heather off the top of my head) has put the URL last and wondered why it didn't attach.  

We could just leave it as is and consider it a trial and error learning process which is fine. Not sure of there's a better way though.

**Comment by brianherbert** [comment]
Looks like this was an issue again for a tester on Twitter: https://twitter.com/timolue/status/327398262095110144

![Screen Shot 2013-04-25 at 9 30 41 PM](https://f.cloud.github.com/assets/106068/425090/fd24c01a-ada3-11e2-847b-b85e18a28bbf.png)

**Comment by evansims** [comment]
I've added a hook for paste events that fires the parser.

**Comment by brianherbert** [comment]
Rad
