### ISSUE TITLE
Change loading messages

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#76]
I really like the loading message that comes up when you are using the typeahead helper that says:

Loading suggestions ... 
This may take a moment on slow connections.

... rather than the (I agree, funny) other messages like "Reticulating splines" which are totally lost on folks without the proper cultural context.

**Comment by evansims** [comment]
:(

**Comment by brianherbert** [comment]
Why if we have an easter egg to enable the current messages? I like them personally.

**Comment by evansims** [comment]
Confirmed fixed in forthcoming UI update.
