### ISSUE TITLE
Twitter embed shows up then it disappears 

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#80]
I see it showing up just fine when I first load the page for a second or two. My guess is something we're doing post-embed to manipulate it is causing it to go blank.

![Screen Shot 2013-04-26 at 11 25 46 AM](https://f.cloud.github.com/assets/106068/428695/b3af53d0-ae18-11e2-991d-1dba41c246bb.png)

**Comment by evansims** [comment]
Fixed
