### ISSUE TITLE
Post create form error handling needs to be added

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#81]
Sometimes post creation won't work. We need to handle those situations otherwise the dialog doesn't know what to do and it just sits and waits. Screenshot shows an example.

![Screen Shot 2013-04-26 at 4 10 34 PM](https://f.cloud.github.com/assets/106068/429356/e08fba20-ae40-11e2-9e17-e3a423d00fa9.png)

**Comment by evansims** [comment]
Confirmed fixed in forthcoming UI update.
