### ISSUE TITLE
Use a URL shortener for links

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#82]
Instead of showing some stupidly long URLs, shorten them using the crwd.mp URL.

**Comment by evansims** [comment]
Implemented.
1. We now transform plain text URIs into anchors.
2. Markdown links are supported.
3. SRC links are always transformed into Bitly shortlinks as a means of defense against malware for users.
4. Link text, if it's the URI, will be shortened to the Bitly link if it's exceptionally long.
5. Link text that isn't the URI is always presented as-is.
