### ISSUE TITLE
We need to find a new site font that accept characters with accents.

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#83]
Lidia, our Polish translator, brought this to my attention. Our site does not display non-latin characters very well. It's actually quite ugly. We should find a different font that keeps with the same similar style that we have now, but supports these accented characters.

![cr1](https://f.cloud.github.com/assets/106068/430334/842f5a9a-ae65-11e2-8076-7ebcbd6fbc92.png)

![cr2](https://f.cloud.github.com/assets/106068/430339/979bfd2c-ae65-11e2-9fcc-156517344aea.png)

**Comment by evansims** [comment]
Eek, that's not good. Our Typekit bundle probably got compiled without full character support.

Example from my account:
![Screenshot_4_27_13_11_21_PM](https://f.cloud.github.com/assets/3093/435282/36b4b1c8-afbb-11e2-9f19-db253df6958c.png)

**Comment by brianherbert** [comment]
Coolio. Waiting on the typekit login.

**Comment by brianherbert** [comment]
Alright, I set this up with all characters supported. We're also on a new typekit account. FTW.

![screen shot 2013-05-01 at 2 38 39 pm](https://f.cloud.github.com/assets/106068/447922/79e6eb92-b221-11e2-8a14-1f087a2c9697.png)
