### ISSUE TITLE
Animated GIF support.

### ISSUE THREAD

**Issue by evansims** [ushahidi/crowdmap-issues#86]
Allow animated GIFs to be uploaded properly via the API; resize each frame when necessary.

**Comment by evansims** [comment]
Done.

**Comment by brianherbert** [comment]
I thought you would at least put a gif in this ticket.

**Comment by evansims** [comment]
![](https://dl.dropboxusercontent.com/u/23890/VDdlb.gif)

**Comment by brianherbert** [comment]
Thank you
