### ISSUE TITLE
Shift + Enter

### ISSUE THREAD

**Issue by eyedol** [ushahidi/crowdmap-issues#88]
Wished I could shift + enter to break a new line when writing a post. Is that a premium feature?

**Comment by brianherbert** [comment]
Posts use markdown without any special key press tricks in the UX so you shouldn't have to hit shift+enter to create a one line break. Simply hitting enter should do that.

I just tested this out and shift+enter submits the form. I'm looking around the interwebs and it seems like people are in two camps on having the textarea go to the next line or submit the post. I'm wondering if posts are something that requires so much speed to require a hotkey.

@evansims thoughts?

**Comment by evansims** [comment]
Hey guys,

Aye, I added Shift+Enter=Submit shortcut after we received a request for it during development. I can't recall who it was now that asked for it; Heather maybe?

I think it's good to have a quick submit shortcut — ultimately I'd like the entire site to be navigatable entirely by keyboard (using gmail style shortcuts) if we can. Personally, I hate reaching for my mouse or trackpad when I feel like I shouldn't have to. But that's just me.

As far as the submit shortcut being shift+enter, I don't have a strong opinion on that particular set. I've seen some sites switch the submit shortcut to Meta/Win/⌘+Enter which I think makes a lot more sense but isn't as universally adopted or intuitive for users to reach for.

**Comment by brianherbert** [comment]
I would be game for the less obvious option. That way people who want it still have it and the folks who are used to using shift+enter for line breaks can still do that, too. I think we would just not do anything on shift+enter entirely since we don't have any special WYSIWYG editor that makes paragraph breaks on a regular press of the return key.

**Comment by evansims** [comment]
Cool, sounds good. Will swap it out to meta+enter for now and see how that feels.

**Comment by evansims** [comment]
Done; I've updated the post and comment dialogs to use meta key + return to submit rather than shift.
