### ISSUE TITLE
Sometimes visiting homepage returns plain 401 error

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#89]
Both @aoduor and @ehersman have reported this bug. Not many details which makes me think this is going to be difficult to diagnose. Erik or Angela, if you guys have any other details about this, that would be awesome.

![image](https://f.cloud.github.com/assets/106068/436664/72620744-b064-11e2-83d0-3f8805fb06ff.png)

**Comment by evansims** [comment]
Hmm, that's an interesting one. Definitely an API communication error from the look of it, but hard to say what it is offhand. Will see if I can reproduce locally.

**Comment by aoduor** [comment]
Well, really, i just try accessing the new crowdmap(https://crowdmap.com/switch/new) from my phone browser, and it returns that error :(. It just happened again right now.

**Comment by evansims** [comment]
Odd. There's no logic to those switch endpoints, they're just two lines of nginx statements: one to set your gatekeeper cookie and the other to redirect you to /.

Can you tell me which URI it chokes on, the switch or the /?

**Comment by aoduor** [comment]
Both :(

**Comment by eyedol** [comment]
Same on android
![img_20130429_214915](https://f.cloud.github.com/assets/73175/441324/d9b32d6c-b116-11e2-9105-99ee382f9af6.jpg)

**Comment by evansims** [comment]
Hmm. Does this happen on both cellular and wifi connections for you both? I've just added some additional debugging info that will be forwarded to myself when you hit this error. If y'all could give it another try to give me some sample data to work with that would be super. Danke.

**Comment by evansims** [comment]
Eureka! The error got triggered and I've found the problem. The sessions in your browsers have expired but we weren't handling that situation correctly. Pushing a fix now; give it another try after a few minutes and let me know if that fixes things for ya.

**Comment by aoduor** [comment]
Yay!!

All good now :)

**Comment by evansims** [comment]
Thanks for reporting this, that was a tricky one! Closing up shop
