### ISSUE TITLE
Uploading a banner image (1.5MB), I get a timeout with no error handling

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/crowdmap-issues#90]
Our form still indicates the file is uploading when there was actually an error.

![Screen Shot 2013-04-29 at 11 05 11 AM](https://f.cloud.github.com/assets/106068/436810/501c822e-b071-11e2-928d-3b21fe06b653.png)

**Comment by evansims** [comment]
Timeout issue was fixed quite awhile ago. UI getting error handling love in forthcoming update.
