### ISSUE TITLE
Allow searching by username

### ISSUE THREAD

**Issue by evansims** [ushahidi/crowdmap-issues#96]
Requested by user ananda

**Comment by heatherleson** [comment]
Add. Search by first name or last name

**Comment by evansims** [comment]
Good call.

**Comment by brianherbert** [comment]
This should already work so this should be considered a bug. I'll handle this one.

**Comment by evansims** [comment]
Ah-ha, I never noticed the dropdown for searching by usernames and maps. So this is already in. Good stuff.

https://crowdmap.com/search/users

There was an issue with the user sanitization filter though that was breaking it. All fixed up now, though.
