### ISSUE TITLE
Location picker locks up Android 4.1.2 browser

### ISSUE THREAD

**Issue by evansims** [ushahidi/crowdmap-issues#97]
I just tried to do a mobile photo post from ny new HTC One; everything worked fine except the location picker. Invoking it completely locked up the browser tab. :(

**Comment by brianherbert** [comment]
Maybe it's too memory intensive? Did it just crash on load straight off the bat?

**Comment by evansims** [comment]
That's what it seemed like; the whole tab just became completely unresponsive. It "felt" like it happened right as we were writing the location layout to the DOM, before the UI throbbers are hidden. I'll do some additional testing and see what I can find.

**Comment by brianherbert** [comment]
I'm debugging in Chrome dev tools, using the profiler to see heap snapshots. The memory consumption doesn't look any different than anywhere else on the site.

Is this still locking up for you? Does it ask for location sharing? Maybe the way we ask to share location is an issue.

**Comment by evansims** [comment]
Yup, I still lock up as soon as I use the location picker. This time I tried it without first attaching a photo but I get the same effect.

**Comment by brianherbert** [comment]
Is there any chance you can use the chrome remote debugging tools to see how much memory the site is gobbling up after opening the picker?

**Comment by evansims** [comment]
OK, this appears to be a Chrome bug. Although I can reproduce the issue in the stable branch every time, I can't from the Beta builds. I'm going to tag this as 'waiting' and will revisit next time I notice Chrome's stable branch gets updated.

Just some notes from my research while troubleshooting this:
1. No errors are raised in the console when the lockup occurs.
2. Timers continue to fire, further confirming it isn't a catastrophic JS failure.
3. Comparing heap dumps between immediately before and after the lockup shows an increase in memory usage of about 1.5MBs, relatively insignificant.
4. We only appear to be using about 7.3MB of system memory with the latest posts view and post creation modal being open. Initializing the location picker bumps this up to 8.8MB.
5. This works fine in Firefox and Chrome Beta channel.

**Comment by evansims** [comment]
Yup, latest Chrome for Android update fixed the lockup. Thank god. Shutting this down.
